jenkinsci/kubernetes-plugin

src/main/java/org/csanchez/jenkins/plugins/kubernetes/BearerTokenCredential.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/BearerTokenCredential/credentials.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-skipTlsVerify.html
OpenShift v3 "origin" do rely on Kubernetes, but with a custom Client certificate / OAuth authorization service. As a result, admin can't use k8s API with plain username/password.
This PR introduce a new credentials type for OAuth Bearer token (afaik there's no plugin to define one already)
PR also introduce option to ignore the TLS Verify step when accessing an https (self-signed) kubernetes master. This mimic openshift CLI `--insecure-skip-tls-verify` option
=> use a Bearer token to connect to API master (typically to connect to openshift origin)

src/main/java/org/csanchez/jenkins/plugins/kubernetes/BearerTokenCredential.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/BearerTokenCredentialImpl.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ServiceAccountCredential.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ServiceAccountCredential/credentials.jelly
alternative impl for https://github.com/jenkinsci/kubernetes-plugin/pull/17
enable a dedicated credential type when jenkins do run inside kubernetes with service account enabled, so cloud can be setup with a fixed configuration, but actual credentials get injected at runtime.
=> Service account

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
This pull request upgrades to the latest Fabric8 client for Kubernetes. 
The new client provides a DSL that makes code easier to read and write.
It has also much smaller footprint and fewer dependencies (no longer using cxf, jaxrs etc).
Last but not least it contains a lot of improvements, reduces complexity etc (and judging from some comments in the source I think they will come in handy). 
Cheers.
=> Migrate to the new fabric8 client for kubernetes.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
The one-shot retention strategy constructor takes a fallback timeout
(in minutes) to use if the task does not signal completion. Setting
this value to zero allows the timeout-based cleanup to race with tasks
starting, which can easily happen for JNLP-launched slaves started by
this plugin. This causes at best the kube pods to be terminated
prematurely, and can lead to worse behavior like leaked pods that
eventually fill up the plugin's simultaneous container limit.
A one minute timeout should not be excessive. Note that the slaves are
still one-shot; upon task completion, the retention policy disables
acceptance.
=> Avoid race with OnceRetentionStrategy timeout

.gitignore
Fix JENKINS-31076 - [kubernetes cli] proper message if credentials are not defined or not found
=> .gitignore for IntelliJ

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-retentionTimeout.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
The default value of one minute introduced in commit 0138277e is small
enough that it trips up jobs with large (~ 1GB, e.g.) images on first
deployment in some settings. This patch bumps the default to 5
minutes and makes it configurable via system property. It seems
*unlikely* that this will be a frequently-adjusted parameter, so
making it part of the plugin configuration settings seems excessively
invasive.
Refs #20.
=> Make OnceRetentionStrategy timeout configurable

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper/help-caCertificate.html
Extend credentials to accept certificates and properly encode certificate and key before passing to kubernetes client config builder.
Fixes [JENKINS-30894](https://issues.jenkins-ci.org/browse/JENKINS-30894)
=> Support client certificate authentication of kubernetes api

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-nodeSelector.html
The following PR adds support for specifying the `nodeSelector` property as part of the pod template. This should allow users to have some control on which nodes a pod might get scheduled on.
I'm marking this as a WIP since I'm new to Jenkins plugin development and there might be a couple of things I missed along the way :sweat_smile:.
=> [WIP] Add support for nodeSelector

src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftBearerTokenCredentialImpl.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl/credentials.jelly
Added support for storing an OpenShift OAuth token as credentials. This is useful especially when using service accounts to communicate between Jenkins and OpenShift
=> Added support for storing OpenShift OAuth access token as a credential

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation/help-key.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation/help-value.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
Pod Annotations are useful. We should be able to create a Pod Annotation in the Template.
I am using them with EC2Metaproxy to grant permissions on AWS.
=> [JENKINS-36253] Add Annotations to Pod Template

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
This remove instanceCap from ContainerTemplate. The field shouldn't be there in the first place. It was copied/pasted from PodTemplate by mistake.
=> Remove unused field from ContainerTemplate.

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodVolumes.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
As the title says, this allows you to do something like this:
```groovy
volumes = [secretVolume(secretName: 'shared-secrets', mountPath: '/etc/shared-secrets')]
podTemplate(label: 'runner', containers: [], volumes: volumes) {
// ...
}
```
Added documentation and tests (didn't run the tests locally though). Tested this on our local Jenkins installation.
Solves my problem mentioned in https://github.com/jenkinsci/kubernetes-plugin/pull/77.
=> allow setting dynamic pod volumes in pipelines

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
When creating a podTemplate via pipeline nodeSelector wasn't being used.
=> Fix nodeSelector in podTemplate

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Null pointer exceptions in 2 places caused the plugin not to work for my setup.
Kubernetes cluster version was 1.6 alpha.
When the queries that are modified below returned 0 items, the getItems() method was returning a null.
=> Fix null pointer exceptions.

README.md, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodImagePullSecret.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/PodVolume.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar/help-key.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar/help-value.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-inheritFrom.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/SubstituteTest.java
This pull request allows a PodTemplate to define a parent template that will be used as a base.
This allows the user to remove repeating/boilerplate code from pipeline and move it in the plugin configuration.
The main benefits are reusability (e.g. don't add the jnlp container everywhere), readability, and more importantly decoupling the pipelines from specific configurations, that might change between environments.
For example: There are environments that may or may not allow the use of hostPath mounts, privileged containers etc. So instead of maintaining two different sets of `Jenkinsfile` inside a project one could just move those `environment sensitive details` in the parent pod, that could even be defined inside the jenkins docker image.
=> Improve the inheritFrom functionality to better cover containers and volumes.

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
* The idea is to re-use slaves after successful builds, the slave is terminated after being idle for the time defined in idleMinutes. That is useful for builds that rely heavily on cached data for "speed".
=> Adding basic retention

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
We were running into the issue the wait is meant to resolve so I tried it out. Looks like the logic got reversed somewhere along the way.
=> Fix logic for waitUntilContainerIsReady

README.md
By default, Jenkins spawns slaves conservatively
https://issues.jenkins-ci.org/browse/JENKINS-39801
=> [JENKINS-39801] Document flags to reduce waiting for executor

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
feat: make pipeline support instanceCap field
fix: containerCap and instanceCap judgement bug
=> feat: make pipeline support instanceCap field

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
Checkboxes in the PodTemplate were being reset to default state in the Views since it seems like Jelly expects the boolean primitive not the Boolean type.
=> Fixing checkbox serialization by jelly views

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateAction.java
```
java.lang.NullPointerException
at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateAction.pop(PodTemplateAction.java:40)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.stop(PodTemplateStepExecution.java:61)
```
=> Prevent NPE in PodTemplateAction.pop

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/WorkspaceVolume.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume/help-memory.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume/help-hostPath.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume/help-serverAddress.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume/help-serverPath.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume/help-claimName.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume/help-readOnly.html
Currently containers share workspace by accessing an empty dir volume inside the pod.
We should also allow the use of other means, like pvc, nfs and hostpath volumes.
This pull request adds an option that alllows the user to choose and configure one of the above.
This is still work in progress (still need to do some more testing), but I am creating the PR for feedback etc.
=> The workspace volume is now configurable.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodImagePullSecret.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
I've tried to align the DSL of the `kubernetes-pipeline-plugin` with this plugin. It seems to work fine, but I am having some issues with some of the types referenced by the DSL not being serializable.
This pull requests makes PodEnvVar and PodTemplate Serializable
=> PodEnvVar and PodTemplate are now serializable.

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-annotations.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/help-annotations.html
Adds the ability to specify a list of annotations to create the pod with.
=> Pod Template "Annotations" Field

CHANGELOG.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
To avoid creating an extra container, the one that exists and the new jnlp auto generated
This would solve the problem for people upgrading from 0.8 and earlier
=> [JENKINS-40847] When upgrading from <0.9 set the container name to jnlp

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
https://issues.jenkins-ci.org/browse/JENKINS-41287
```
[job with spaces] Running shell script
Executing shell script inside container [busybox] of pod [kubernetes-8557fdf9781e4cf2a61886465194237f-38066e920443]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/job with spaces@tmp/durable-aa4b60a9/pid'; jsc=durable-e34518f433054f84ad6d3027eca192a2; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/job with spaces@tmp/durable-aa4b60a9/script.sh' > '/home/jenkins/workspace/job with spaces@tmp/durable-aa4b60a9/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/job with spaces@tmp/durable-aa4b60a9/jenkins-result.txt'
/home/jenkins # cd "/home/jenkins/workspace/job with spaces"
/home/jenkins/workspace/job with spaces # sh -c echo $$ > '/home/jenkins/workspa
ce/job with …
```
=> [JENKINS-41287] Fix error when job contains spaces

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Since the mounting a drive at `/home/jenkins` wipes out the directory (which has dot files we'd like to keep around), I wanted to mount the workspace in a subdirectory. Unfortunately, by overriding `HOME` we can't use the dotfiles. This sets a default `HOME` to be the workspace directory but allows an override from either the pod or container config. Also removes duplicate env vars from being sent to be more explicit.
Wasn't sure how best to test this since `createContainer` (and its callers) are all private, and no other examples exist in `KubernetesCloudTest`.
=> Cleanup environment variable mapping, allow overriding HOME env variable

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
With this PR, you can set `name` in the `podTemplate`, and the pod launched in K8s will have the name set (with random UUID at the end). It will also sets the Jenkins Node name.
=> Make the name field in the pod template the pod name

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
This fixes a simple bug where in some cases, instead of the template's `workingDir`, the `command` value is copied.
=> Fix workingDir inheritance error

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
I'm not entirely sure on this one, but since the `inheritFrom` field is supposed to contain a `name`, the nesting stack should also contain `name` instead of `label`.
I was not able to run all tests, but this fixes my problems with nesting `podTemplate` on my Jenkins instance.
=> Use name instead of label for the nesting stack

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-slaveConnectTimeoutStr.html
For certain slaves, there might be a need to perform some runtime
configuration/steps after getting scheduled, but before starting the
jenkins job. The default timeout of 100s might not be sufficient for
such a scenario. To cater to this use case, this patch introduces the
ability to configure the slave to jenkins connection timeout, defaulting
to 100s for backwards compatibility.
=> Make Slave 🠦 Jenkins conn. timeout configurable

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
This PR has two small changes. Hope that it's alright that they're both in one PR. They're closely related.
The first fixes a bug where the plugin fails to use a pod if the pod's name is over 63 characters. I believe this is due to the fact that the JNLP container has a max hostname of 64 bytes (including the null terminator).
```
$ getconf HOST_NAME_MAX
64
```
As as a result, when [`workspace.child(HOSTNAME_FILE).readToString()`](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java#L44) is executed, it returns the first 63 characters of the pod name, which causes the plugin to look for the wrong pod.
The second change makes the random string appended to the end of the pod name more like …
=> Limit pod name to 63 characters, and shorten randomly generated string

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
It looks too easy. 
Please let me know if there is a reason not to use command's pwd.
=> Fixed: JENKINS-40925 - dir context is not honored by shell step

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
We need the random names because the PodTemplates that we generate using the pipeline are added to the cloud configuration. Using user provides names has the following side effects:
- Two builds using podTemplates with the same name can get in each other way
- It's possible to mess up with preconfigured podTemplate (found in config.xml)
=> Restore random naming for pipeline managed pod templates.

README.md, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/NamespaceAction.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runDirContext.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithExistingTemplate.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestart.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runJobWithSpaces.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenNamespace.groovy
This pull request, adds support for namespaces inside the PodTemplates.
This feature can be really useful, if we need to create `ephemeral` namespace to run our builds and tests. For example: 
- create a namespace 
- deploy all apps and services 
- run end to end tests 
- then destroy namespace.
=> Add namespace support on PodTemplate.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Most actions that create resources in Kubernetes are asyncronous, because the
controller-manager needs to update resources, and perform extra work
asyncronously after an API call is made to create a given resource, thus it is
possible to do a POST + GET, and not see the resource just POSTed.
The current code incorrectly assumed that if the CreatePod API call succeeded,
that the pod will exist by the time we wait for containers to become ready.
This pull-request updates the logic to query for the pod mulitiple times before
deciding it doesn't exist.
=> Wait for pod to exist up to 60 seconds before erroring

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
[JENKINS-41758](https://issues.jenkins-ci.org/browse/JENKINS-41758)
Ok, I think this is ready to go.
cc @reviewbybees esp @carlossg
=> [JENKINS-41758] Add a Declarative Agent extension for Kubernetes

src/main/kubernetes/gke.yml, src/main/kubernetes/minikube.yml
See thread @ https://github.com/kubernetes/minikube/issues/1239 for background on `storageClassName: ""` and `namespace: "kubernetes-plugin"` changes.
=> minikube update

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy
The changes will allow to add a command liveness probe to a container. You can specify:
command to execute (does not support httpGet) - required field
timeout seconds
initial delay seconds
failure threshold
period seconds
success threshold
=> Add command liveness probe support

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PortMapping.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PortMapping/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PortMapping/help-containerPort.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PortMapping/help-hostPort.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PortMapping/help-name.html
This is to finish up the port mapping ticket in #135.
I added the help documents, and i can fix the other issue if @carlossg and provide guidance on how it should be fixed.
=> Port mapping

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
after using a build pod it can be common to wait for a pipeline approval, this change means the build pod doesn't hang around once we've finished with it
=> delete the build pod after we have finished with the template block

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
**Changes**
Rename the methods
- setEnvVars 
- setAnnotations
- setImagePullSecrets
to use `add` syntax
- added methods for setting. i.e. overwrite the existing array.
**Motivation**
The names of the methods currently `set<Object>` indicates that you are setting a new value rather than adding to an existing array.
=> refactoring add/set methods

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
This fixes an issue where if you only had PodTemplates defined that were set to usage mode Exclusive containers would get scheduled but Jenkins would be unable to schedule any jobs on them.
The Kubernetes plugin now returns false to canProvision() if it doesn't have any templates it can use and which can be used to schedule the requested workload.
=> Don't provision nodes if there are no PodTemplates set to usage mode Normal

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
Where your Jenkins project contains spaces, the temporary kubectl config file will also create spaces.  The file location need to be wrapped in quotes to work with the kubectl shell commands.
For example: 
kubectl config --kubeconfig="My Jenkins Project/.kube8017077765813839285config" use-context k8s
rather than:
kubectl config --kubeconfig=My Jenkins Project/.kube8017077765813839285config use-context k8s
=> Fix: Spaces in Jenkins project name

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Fallback on Kubernetes Namespace if template namespace is not defined. Otherwise, you might experience a Service account permission problem.
=> Protect if podtemplate's namespace is not defined

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-maxRequestsPerHostStr.html
First of all, `Launcher.launch` is called not once, but again and again.
I.e. overwriting shared members of the enclosing class that a different
thread is still using (and only cleaning the ones that were written last).
That is a bad idea, and caused the thread and connection leak.
So, move them (`watch` and `proc`) to local variables, and close them
elsewhere:
* `watch` was already cleaned up in `ContainerExecProc`
* `proc.kill()` was not correctly executed anyway, and this is still broken. See discussion below.
Second of all, `waitQuietly` on the `started` latch was what caused
the "pipe not connected" errors:
In case of InterruptedException, it caused the launcher to just continue
as if `started` had already been counted down (i.e. the websocket connection
established), when in reality …
=> JENKINS-40825 close resource leak, fix broken pipe error

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenNamespace2.groovy
=> [JENKINS-45910] Delete pods in the cloud namespace when pod namespace is not defined

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud/config.jelly
The idea behind this change is to manage configuration of Kubernetes Cloud through other means than the UI, in the context of multiple Jenkins instance infrastructure, and prevent the configuration from being modified when accessing the Manage Jenkins/Configure system page.
=> Allow to create non-configurable instances programmatically.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerEnvVar.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_0_12/config.xml
Upgrading from 0.12 causes
class org.csanchez.jenkins.plugins.kubernetes.PodEnvVar is missing its descriptor
=> Fix #162 error PodEnvVar is missing its descriptor

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesNodeContext.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/Resources.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help-limitBytes.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help-name.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help-returnLog.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help-sinceSeconds.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help-tailingLines.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep/help.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/getContainerLog.groovy
Please don't merge yet, as I will add the missing parameters that the API supports
(`withTerminatedStatus sinceSeconds sinceTimestamp withTailingLines limitBytes`).
I just wanted to get early feedback, especially on the way I extracted the common code from `ContainerStepExecution`.
=> JENKINS-46085 containerLog step to get the logs of a container running in the slave pod

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-containerCapStr.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-instanceCapStr.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/help-instanceCap.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
With current behavior
It is inconsistent, probably needs to be fixed https://issues.jenkins-ci.org/browse/JENKINS-45845
=> [JENKINS-45845] Change containerCap and instanceCap 0 to mean do not use

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
This PR enable to redefine default slaveConnectTimeout for podTemplate declared in pipeline, eg.
```
podTemplate(
label: 'mypod', 
containers: [
containerTemplate(name: 'busybox', image: 'busybox', ttyEnabled: true, command: '/bin/cat'),
],
slaveConnectTimeout: 200
) {
node ('mypod') {
stage('Run') {
container('busybox') {
sh 'echo "pwd is -$(pwd)-"'
}
}
}
}
```
=> Enable setting slaveConnectTimeout in podTemplate defined in pipeline

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
There are a number of dependencies declared by the plugin which are actually not required, or that can be made optional.
Here is a recap of the list of changes
Moved to test scope:
* `workflow-cps`
* `workflow-durable-task-step`
* `workflow-support`
Moved to optional
* `pipeline-model-extensions`
-> This requires to add a dependency to `variant` in order to leverage `@OptionalExtension`
Removed
* `pipeline-model-api` as the plugin doesn't depend on it explicitly (only through `pipeline-model-extensions`)
=> Remove unneeded dependencies

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Added equals and hashCode overrides to podAnnotations so that combining doesn't allow duplicate keys  Also, changed precedence so that the template will override the parent in inheritance.
=> Pod annotations cannot contain duplicate keys when combining pod templates

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
https://issues.jenkins-ci.org/browse/JENKINS-46719
=> [JENKINS-46719] Check if container exists in pod at all

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenEnvVars.groovy
This PR enables redefining default env variables like HOME and removes duplicated env vars for created containers.
It fixes regression introduced in https://github.com/jenkinsci/kubernetes-plugin/pull/162/files#diff-14316beac1f1489a56a52e21cf8e0ee6R371
After bumping kubernetes-plugin to version 1.0 redefining HOME env variable doesn't work.
One of our pipeline where we need to redefine HOME variable for a container in a podTemplate stopped working.
```
podTemplate(label: 'mypod',
containers: [
containerTemplate(
name: 'mongodb', 
image: 'bitnami/mongodb:3.4.5-r0',
envVars: [
envVar(key: 'HOME', value: '/root'),
]
)
]
)
{
node ('mypod') {
stage('Check mongo') {
container('mongodb') {
sh """
mongo version
"""
}
}
}
}
```
On kubernetes-plugin version 1.0 mongodb container starts with …
=> Fix overriding HOME env var and remove duplicated env vars

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
To avoid the log warnings
Slave -> Jenkins connection timeout cannot be <= 0. Falling back to the default value: 100
=> Default podTemplate slaveConnectTimeout to 100

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Prevent to start builds that might try to use containers
that haven't started (or will never start due to errors).
This reverts a change in behavior introduced in #217, see https://github.com/jenkinsci/kubernetes-plugin/pull/217#issuecomment-330595381.
=> Only allow tasks after all containers in pod are ready

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVarsFromContext.groovy
Simple escape for quotes on environment variables to avoid dangling multi-line variables during 'export' part of container.
=> JENKINS-46670: Escape quotes in environment variables

README.md
My team spent days trying to figure this out. With enough Kubernetes experience this wouldn't be an issue for an engineer but I think this is a note worth adding. Atom cleaned up some hanging whitespace in the process.
=> add documentation about pod token with Kubernetes Service Account

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Otherwise it will fail with
io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.
Test pod creation on global config page
=> If namespace is not provided nor autoconfigured should use default

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java, src/test/java/org/jvnet/hudson/test/RestartableJenkinsNonLocalhostRule.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/getContainerLogWithRestart.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestartWithLongSleep.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestartWithMultipleContainerCalls.groovy
[JENKINS-47476](https://issues.jenkins-ci.org/browse/JENKINS-47476)
[FIXES JENKINS-47476]
=> allow re-use of existing pods for restarts

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Sometimes it can be failed to delete a pod slave with following trace.
```
Nov 13, 2017 5:51:01 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
SEVERE: Failed to terminate pod for slave *****
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: *****
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:268)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.ja …
```
=> Wait for complete disconnection with pod slaves

Jenkinsfile-kubernetes, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
To prevent multiple tests running simultaneously to collide with each other.
Only separating master from the rest for now
=> Test branches in separate namespaces if they exist

README.md
Some of the current documentation and examples in the Readme are misleading.
This brings them inline with the snippets under the examples directory.
=> fix-readme - fix misleading code blocks

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Adding new line when printing out the logs
before:
after:
=> add new line when logging the agent in jenkins

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Apparently it is needed or jenkins will think failed nodes are still available in some cases,
not calling the plugin again to provision nodes,
thus leaving jobs stuck waiting for executor that will never be created
Based on yet-another-docker-plugin which was mentioned by @stephenc as a good example of cloud api implementation https://github.com/KostyaSha/yet-another-docker-plugin/blob/db0026ea46b1ca24a03c4212d09acefff0b1f2e4/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java#L281
=> Missing call to slave.terminate()

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
=>  [JENKINS-49166] Store definition of dynamic templates to a separate configuration than kubernetes cloud

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/buildPropertyVars.groovy
[JENKINS-49465](https://issues.jenkins-ci.org/browse/JENKINS-49465)
This solves a small but critical issue where, within declarative pipeline container step, build environment variables are not available. 
This also removes the odd "JAVA_HOME" #245 work of obtaining builtins as we only need to that to determine if the executor is being called from either Jenkins proper or through another plugin. 
This work was based off reading https://github.com/jglick/pipeline-plugin/blob/e19ac3608789e841eed2bdd90aff35bc9bd74dc9/support/src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java#L68
=> JENKINS-49465: Provide injection of run context

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithDifferentShell.groovy
We need to be able, in our containers, to load profile files (.bash_rc, .profile, ...) at runtime. /bin/sh, while it's often just a link to /bin/bash puts you in a compatibility mode that doesn't load these files.
We run this Jenkins plugin against an OpenShift cluster that, by default, runs containers with an undefined UID. Being able to load variables from "profile" files is critical for us.
The implementation is retro compatible with the already written jenkinsfiles, but let's you override the interpreter you will use to run commands in your container (in our case, we mostly want to use bash).
An example of Jenkinsfile with the modification:
```
podTemplate(name: 'maven', label: 'maven', containers: [
containerTemplate(name: 'maven', image: 'maven:latest', ttyEnabled: true, command: …
```
=> Allow specifying a different shell command other than /bin/sh

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVarsFromContext.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/sshagent.groovy
This fixes the long outstanding issues with plugin contributed envVars and should allow EnvVars to work as expected when compared to any other executor provider.
=> JENKINS-42582: fix nondesired injection of computer variables into container

README.md
Complete nit - copy/paste of the example blew up because of the `#` character, so updating this example to the groovy style single-line comment syntax
=> changing to groovy style comment

src/main/kubernetes/jenkins.yml
Otherwise a plugin installation causes 2 restarts
[JENKINS-49956](https://issues.jenkins-ci.org/browse/JENKINS-49956)
=> [JENKINS-49956] Wait for up to 2 minutes before killing the container

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
~~Note: this is a WIP because it is blocked by this PR on the fabric8 kubernetes-client: [config: support loading from kubeconfig string](https://github.com/fabric8io/kubernetes-client/pull/1029).~~
~~* Updates to the 3.x version of the `kubernetes-client` package~~
* Supports `kubeconfig` files (`secretFile` credentails) as cluster credentials
I have (minimally) tested it, however. Sending it now so people can take a look. I'll update the title when it's no longer blocked.
This is my preferred way of handling all credentials for kubernetes clusters, whenever the credentials are "portable" and sealed. For example, when producing limiting service accounts in remote namespaces and then generating kubeconfigs for them.
Fixes: [JENKINS-49817](https://issues.jenkins-ci.org/browse/JENKINS-49817) …
=> [JENKINS-49817] Support kubeconfig from secretFile credentials

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PlannedNodeBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PlannedNodeBuilderFactory.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ProvisioningCallback.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/StandardPlannedNodeBuilder.java
* New extension point PlannedNodeBuilderFactory to allow extensions to provide alternative PlannedNode implementations.
* Builder pattern for KubernetesSlave to stop the explosion of constructors
=> Allow customization of NodeProvisioner.PlannedNode using extension point

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVarsFromContext.groovy
[JENKINS-50437](https://issues.jenkins-ci.org/browse/JENKINS-50437)
Caused by [JENKINS-42582](https://issues.jenkins-ci.org/browse/JENKINS-42582) #291 
https://github.com/jenkinsci/kubernetes-plugin/pull/291/files#diff-d7c591c5115c154bd8394f3479e07131
=> [JENKINS-50437] Env vars using PATH+SOMETHING syntax clear the previous env var

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
First shot at printing agent specification upon first use.
This prints the docker image used for each container as well as the resource constraints if they are defined.
=> Print agent specification upon node allocation

README.md, examples/maven-yaml.groovy, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodFromYaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-busybox.yaml
To avoid having to manually add fields for all possible options current and future, just pass the yaml to be used as base.
Yaml is merged with other fields (if set) as it if were a parent Podtemplate
=> [JENKINS-50282] Allow creating Pod templates from yaml

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/HostPathVolume.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-busybox.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
Volume mounts were being compared by name instead of mountPath which needs to be unique per container
[JENKINS-50525](https://issues.jenkins-ci.org/browse/JENKINS-50525)
=> [JENKINS-50525] Fix duplicated volume mounts

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
This defaults to client namespace as before. Currently it logs the `master` namespace, even if the slaves are being provisioned elsewhere.
=> Use slave template namespace in logs

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
with provided jnlp container in yaml
[JENKINS-50533](https://issues.jenkins-ci.org/browse/JENKINS-50533)
=> [JENKINS-50533] Merge default jnlp container options

README.md, examples/README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYaml.groovy
Using the yaml syntax
[JENKINS-50533](https://issues.jenkins-ci.org/browse/JENKINS-48135)
Supersedes #260
Example:
```groovy
pipeline {
agent {
kubernetes {
label 'mypod'
defaultContainer 'jnlp'
yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
some-label: some-label-value
spec:
containers:
- name: maven
image: maven:alpine
command:
- cat
tty: true
- name: busybox
image: busybox
command:
- cat
tty: true
"""
}
}
stages {
stage('Run maven') {
steps {
container('maven') {
sh 'mvn -version'
}
container('busybox') {
sh '/bin/busybox'
}
}
}
}
}
```
=> [JENKINS-50533] Support multiple containers in declarative pipeline

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-yaml.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
…lerations
Per discussion in https://github.com/jenkinsci/kubernetes-plugin/pull/275#issuecomment-380215507 and https://github.com/jenkinsci/kubernetes-plugin/pull/275#issuecomment-380217480
And for https://trello.com/c/XBOXKjYA/1446-3-add-pod-tolerations-to-slave-pods-jenkinsintegration
@carlossg @bparees fyi / ptal
=> Expose pod cfg via yaml to UI and merge tolerations

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
If you have a `PodTemplate` with a ContainerSpec, and want to also set the `yaml` field to apply some things that aren't directly configurable through this plugin, then it's possible to hit NPEs if resource requests / limits aren't set.  (In Kubernetes, it's perfectly valid not to set resource request / limit values for `cpu` and memory.)
This PR defensively codes to cover that case.
=> Resolve NPE merging yaml when resource requests/limits are not set

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
They haven't been needed for a while and can't be merged easily from parent to children
Fixes regression introduced in #305
=> [JENKINS-50913] Do not pass arguments to jnlp container

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Really 3 things going on in this diff:
1) I found that setting idle timeout wasn't keeping slaves around - they'd get killed once each job finished. Tracking this down - it turned out combine ( PodTemplate, PodTemplate ) was creating a new object to copy data into but was copying an incomplete set of data in - dropping a number of fields. These are now copied in similar to the existing fields - preferring template over parent. 
2) Added some logging in combine for PodTemplate to mimic what already existed for combine for Pod. 
3) Added a simple unit test for the remaining non-deprecated fields on PodTemplate.
=> Ensuring all data on pod template is copied during combine

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
because labels are empty
Supersedes #322 #320
=> [JENKINS-50268] instanceCap reached with preexisting pods

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplateTest.java
The copy constructor is very useful when creating a new template based
on an existing one. The new container usually needs some config changes
without affecting the original container.
=> Add copy constructor for ContainerTemplate

pom.xml
JCasC Plugin CI is now failing due to the upper bounds checks on libraries.
I propose to switch K8s plugin to use API Plugins instead of directly bundled libs.
CC @ewelinawilkosz @ndeloof @carlossg 
@reviewbybees
=> [JENKINS-51582] - Use Jackson and Apache HttpComponents Client libraries from API plugins

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
it will run pods in the same namespace as the master
```
May 30, 2018 10:38:01 AM WARNING org.kohsuke.stapler.RequestImpl injectSetters
Cannot access property namespace of class org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud
java.lang.IllegalArgumentException
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:72)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.setNamespace(KubernetesCloud.java:241)
Caused: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```
=> Namespace is not really required

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecutionTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badcontainername.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badcontainernameyaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badlabel.groovy
Initial approach to providing validation and immediate job failure on bad label and name. 
Please review correctness of regex and if throwable Exception should be changed.
=> [JENKINS-51248] Added label and container regex to fail job if bad

CHANGELOG.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
=> [JENKINS-51248] Fix label validation regex

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java
Use the error websocket stream to get the info
Depends on https://github.com/fabric8io/kubernetes-client/pull/1045
=> [JENKINS-50392] Get the exit code the correct way

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Currently, if an unsupported directive is used in `PodTemplate.yaml` (e.g. the `envFrom` directive of a container), then this directive is discarded by `combine(Container parent, Container template)`. This PR fixes this.
Additionally, `envFrom` is now supported by concatenating the `envFrom` directives of parent and template.
=> Preserve unsupported directives in PodTemplate.yaml, add explicit support for envFrom

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Use Unix path separator in volume mount paths
Signed-off-by: Alex Johnson <ajohnson@bombora.com>
=> [JENKINS-47178] Replace Windows path separator with Unix path separator

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-busybox.yaml
Combine all resources declared in `requests` and `limits`, not just the currently hardcoded CPU and memory. This allows users to declare other resources such as GPUs in their YAML fragments. The pipeline API itself still only allows CPU and memory to be changed.
=> Combine all resources declared in requests and limits not just CPU and memory

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
I have an issue when running launcher.launch().stdout(listener) from a different plugin. 
**Background**: 
ContainerExecDecorator decorates the launcher. 
**The issue:**
ContainerExecDecorator's `doLaunch()` gets an OutputStream and splits the output to both the OutputStream and launcher's logger. In my case, OutputStream and and launcher's logger are the same.
**Expected:** All lines printed properly in job's log
**Actual:** Lines are printed twice in job's log
**Reconstruction:**
Run [this line](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/maven-example/Jenkinsfile#L18) inside a pod:
```
container('maven') {
rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install', buildInfo: buildInfo
}
```
=> Avoid streaming to 2 similar OutputStreams

CHANGELOG.md, Jenkinsfile-kubernetes, README.md, examples/declarative_from_yaml_file/Jenkinsfile, examples/declarative_from_yaml_file/KubernetesPod.yaml, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYamlFile.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeYamlFile.yml
[JENKINS-52259](https://issues.jenkins-ci.org/browse/JENKINS-52259)
If given, it'll read from the specified file via `readTrusted` and use
that for the yaml to pass on.
I don't have a local k8s env on my laptop so I haven't actually tested this yet. =)
=> [FIXED JENKINS-52259] Add yamlFile option for Declarative agent

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateAction.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Always.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Default.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Never.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/OnFailure.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetention.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetentionDescriptor.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-podRetention.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-podRetention.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/help-podRetention.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetentionTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRetention.groovy
New configuration to control how the kubernetes-plugin deletes
slave build pods.
* Support for cloud and pod template configurations in Jenkins UI
* Groovy support for pipeline builds
OpenShift Bug [1515940](https://bugzilla.redhat.com/show_bug.cgi?id=1515940)
=> [JENKINS-48149] Add Pod Retention policies

pom.xml, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
[JENKINS-52623](https://issues.jenkins-ci.org/browse/JENKINS-52623)
Tada! Regrettably, I had to use an external repository for the test, though.
Basically replaces https://github.com/jenkinsci/kubernetes-plugin/pull/286
cc @carlossg
=> [FIXED JENKINS-52623] Use Declarative's CheckoutScript to populate env

README.md
current version the pods label is `jenkins=slave` 
and Flag --show-all has been deprecated, will be removed in an upcoming release
=> update deleting pods in bad state 

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Fix for JENKINS-50879. I re-activated the "PodTemplateBuilderTest.testBuildFromTemplate" test which was failing without this patch.
=> [JENKINS-50879] Add volumes from pod template to JNLP container

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
We met a weird issue when migrating the scripted syntax to declarative
with Kubernetes plugin: The `Launcher` doesn't forward `stdin`,
`stdout`, or `stderr` even though they are requested to be forwarded.
This breaks many plugins that use `Launcher` to start a remote process on Jenkins slaves.
This happens because when Kubernetes plugin converts declarative syntax to scripted syntax,
all build steps are enclosed with a `container` statement.
As a result, remote commands are run via the Kubernetes exec API rather than
the jnlp agent.
Since running steps via Kubernetes exec API is still considered ALPHA
and there are some compatibility issues to solve,
I would like to make a small change to the syntax converting process:
The declarative steps will not be enclosed with a `container` …
=> [JENKINS-53422] Declarative: do not wrap steps with `container` statement unless default container is changed

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/podLog.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
I don't know whether there will have a kubernetes environment, so I don't offer a test case.
=> Add Pod log for kubernetes agent

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputerFactory.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Kubernetes Computer ExtensionPoint
Similar to #238, we would like to add metadata of the running jenkins jobs to
the pods.
Ideally we would like to have the JOB_NAME, BUILD_NUMBER, BUILD_TAG (of which
may or may not be meaningful) available in the pods. Unlike #238, we
would like to use labels not annotations as it is easier to correlate those in
prometheus using the kube_node_labels series.
In our discussions we've realized that the display name of a job may differ
based on the job type and our naming scheme would only hold for certain jobs
and it is difficult to come up with a generic solution (especially keeping in
mind that label values can only use the following chars :[a-z0-9A-Z], dashes
(-), underscores (_), dots (.)).
One of the solutions we can think of is to create an extension …
=> Allow adding jenkins job metadata to the pods using the KubernetesComputer extenion point

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesNodeContext.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
=> [JENKINS-53297] Use data we have from KubernetesSlave instead of introspecting

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Hi Maintainers
this fix will add missing -tunnel option at
$JENKINS_URL/computer/$JENKINS_NAME/slave-agent.jnlp endpoint
This will make possible to use command to launch agent independent whether jenkins is behind load balancer or not
=> populate jnlp tunnel in the jnlp endpoint

examples/kaniko-declarative.groovy, examples/kaniko.groovy
Lock version to avoid breaking changes in Kaniko, e.g. https://github.com/GoogleContainerTools/kaniko/issues/482
=> kaniko needs another dir in the path

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-waitForPodSec.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
Allow users to modify how many times we will try to reconnect to the pod
and how much time to sleep between each reconnect attempt. In cases
where the Kubernetes cluster is under high load, we might want to reduce
the amount of API calls.
Signed-off-by: Daniel Belenky <daniel.belenky@gmail.com>
=> Parametrize how long to wait for pod to be running

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
Added a SaveableListener to invalidate cache when Jenkins object is
being saved.
Instead of blindly closing the KubernetesClient when evicted from the
cache, put it in a list to monitor. Then every minute,
`PurgeExpiredKubernetesClients` will check if there are still http connections
and close it when it becomes unused.
=> [JENKINS-55138] Don't close kubernetes client upon cache removal

pom.xml
[Issue](https://issues.jenkins-ci.org/browse/JENKINS-55234)
Updating the parent pom so we can benefit from the Mockito Managed version.
@jenkinsci/java11-support
=> [JENKINS-55234] Update parent pom to benefit from new Mockito version

Jenkinsfile, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
=> Do not wait for agent connection if pod has failed

src/main/java/org/csanchez/jenkins/plugins/kubernetes/DefaultInProvisioning.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNamespaceFromYaml.groovy
**Proposed changelog entries**
- Fixes the declarative agent can't set the namespaces
=> [JENKINS-51610] Allow setting namespace from Pod yaml

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
* combine env vars before writing once into the container
=> JENKINS-50429 combine env vars into a single set before writing once

README.md
When validate that the certificate works, the --cert-type option is missing.
From the curl man page :
> If --cert-type is missing from the curl command 'PEM' is used by default
but we use a P12 certificate type
=> Added missing --cert-type option for certificate check

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithSlaveConnectTimeout.groovy
All issue details here:
https://issues.jenkins-ci.org/browse/JENKINS-55960
Changeset:
1. Added `slaveConnectTimeout` and `namespace` to Declarative Pipeline class.
=> [JENKINS-55960] Missing DeclarativePipeline podTemplate parameters

examples/kaniko.groovy
The kanikos.groovy example had the executor flags --insecure and --skip-tls-verify improperly formatted. 
This attempts to resolve that.
=> kaniko.groovy fix argument spacing

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
This is an attempt to give "nodeUsageMode" more visibility, due to a "race-condition" discovered while this was set to its default value "NORMAL" (other jobs "stealing" the pod from a job).
PS: Having `@DataBoundSetter` on two overloads of the same method seems to confuse the snippet generator... Switching the order of those cases fixed it for me... (Maybe removing the non-String version is the "correct" fix, but might break backwards compatibility)
=> Set nodeUsageMode to EXCLUSIVE as default

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
- no information leakage, just avoid stacktrace
Different approach proposed to improve #419.
See [JENKINS-56155](https://issues.jenkins-ci.org/browse/JENKINS-56155).
=> [JENKINS-56155] Allow non-admin to call the methods to ease API usage

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
=> [JENKINS-56140] Expire Kubernetes clients after one day

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Replaces the active wait by a proper watcher.
Submitting this to get the testing to run.
=> Use a watcher to monitor pod status while launching the agent

pom.xml
https://github.com/fabric8io/kubernetes-client/releases/tag/v4.1.2
This version includes numerous fixes, namely (for me) https://github.com/fabric8io/kubernetes-client/issues/1332, which will fix a regression that prevented authentication using aws-iam-authenticator.
=> [JENKINS-52593] Update kubernetes client to 4.1.2

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Fixes #425
Works around https://github.com/fabric8io/kubernetes-client/issues/1008
=> [JENKINS-50429] Use a bigger buffer for stdin on kubernetes exec

examples/maven-with-cache.groovy
Some of the plugins being build expect Maven version 3.5+, else the build fails.
So updating to 3.6.0 as that is the current version, confirmed it builds with this.
=> update maven version for compatability

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
as it is being cached and reused
=> [JENKINS-55392] Do not close Kubernetes client after containerLog step

pom.xml, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
Analogous to the fixes in https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/322 ([JENKINS-56544](https://issues.jenkins-ci.org/browse/JENKINS-56544)), since this `DeclarativeAgentScript` has the same problem.
Fixes issues where parallel stages with failFast would cause the build result to be aborted instead of failure in some cases. Easiest to review the [whitespace-reduced diff](https://github.com/jenkinsci/kubernetes-plugin/pull/445/files?w=1) since this just removes a try/catch and de-indents the block. Happy to re-indent to avoid touching the lines if desired.
CC @abayer
=> [JENKINS-56544] Don't set build result in Declarative agent blocks

Jenkinsfile, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Making sure this plugin is constantly checked both building with JDK8 and JDK11.
This goes with the Jenkins Java 11 General Availability announcement made back in March, and we're making a pass to check plugins are looking good on a JDK11.
([to understand the Jenkinsfile content](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime))
@jenkinsci/java11-support
=> Java 11 readiness: build both on JDK8 and JDK11

src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/help-defaultMode.html
Addressing [JENKINS-49641](https://issues.jenkins-ci.org/browse/JENKINS-49641)
This change allows you to specify defaultMode for a secretVolume in the podtemplate.
Currently when using SSH private keys in a secret volume, you must specify using YAML in the podTemplate in order to get the correct permissions on the files.
I have tested this it works with and without the defaultMode specified to maintain backwards compatibility.
=> Allow Setting Default Mode In Secret Volumes

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
https://issues.jenkins-ci.org/browse/JENKINS-56121
Based on https://github.com/jenkinsci/kubernetes-plugin/pull/451 @fredg02
Since the raw yaml can add quite some noise to the console log, an
option was added to disable it. Default is ShowRawYaml=true, so the
default behavior does not change.
=> [JENKINS-56121] Add option to (not) show raw yaml in console

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_1/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_1/credentials.xml
Although I don't see were it could come from
Added logging to debug it
=> [JENKINS-57116] Fix empty yamls introduced on upgrade to 1.15.1

examples/README.md
The original path does not exist relative to `kubernetes-plugin/examples`.
Absolute path works as expected.
=> fix examples link

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
[JENKINS-57827](https://issues.jenkins-ci.org/browse/JENKINS-57827)
You cannot define a property in _both_ `@DataBoundConstructor` _and_ `@DataBoundSetter`.
=> [JENKINS-57827] Fix databinding of ContainerTemplate so DescribableModel.uninstantiate2 works

pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9
=> update jackson from 2.9.8 to 2.9.9 CVE-2019-12086

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateMapTest.java
- In some situations in a high-load environment where many builds are being triggered, it is possible for 2 templates to be added at same time.
-  The consequence is that only 1 podTemplate is added and the other build is left in a neverending state whereby the console log says:
"Waiting for podABC ..."
- One workaround was to rebuild the build that was hung (which essentially re-adds the podTemplate). This enabled the hung build to become unstuck.
=> Ensure adding dynamic pod template is thread-safe

Jenkinsfile-kubernetes
Like in https://github.com/jenkins-infra/pipeline-library/pull/90. I have enabled the global setting on the server running this. But as usual, I have no write access to the repo so this PR build will not verify my change.
=> No need for timestamps step any more

CHANGELOG.md, pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodFromYaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithExistingTemplate.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariables.groovy
[JENKINS-57893](https://issues.jenkins-ci.org/browse/JENKINS-57893)
@Vlatombe
=> [JENKINS-57893] Mask Kubernetes secrets bound to containers in build log

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Amends #427, since in a build from #503 I saw an apparently unrelated flake
```
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
at io.fabric8.kubernetes.client.internal.readiness.ReadinessWatcher.await(ReadinessWatcher.java:58)
at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.periodicWatchUntilReady(HasMetadataOperation.java:192) …
```
=> Removing short timeout on ContainerExecDecoratorTest.testContainerExecPerformance

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java
Looks like I missed it when I initially introduced the extension point in https://github.com/jenkinsci/kubernetes-plugin/pull/288
=> Fixed an issue where only the last PodTemplateFilter would be applied

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecutionTest.java
Downstream of https://github.com/jenkinsci/workflow-job-plugin/pull/131. Supersedes an attempt made in #490. @Vlatombe
=> [JENKINS-46076] Hoping that workflow-job-plugin #131 will fix a flake in PodTemplateStepExecutionTest.testBadLabel

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
=> Add a unit test for the `showRawYaml` option

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Currently the kubernetes plugin does not support to list and use a credential type of Docker Host Certificate Authentication.This PR will enable this . Please help check that if it is allowed to be merged. Thanks
Signed-off-by: Shuwei Hao <haoshuwei24@gmail.com>
=> support Docker Host Certificate Authentication type

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
Record http connections count for diagnostic purpose
=> Add http connections count

src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl.java
[JENKINS-49717](https://issues.jenkins-ci.org/browse/JENKINS-49717) The "OpenShift OAuth token" is still available when creating new credentials but actually unusable. This fix will hide it from the dropdown when creating new credentials. Existing credentials are still selectable in the Kubernetes Cloud configuration, I believe thanks to the [aliases](https://github.com/jenkinsci/kubernetes-plugin/blob/kubernetes-1.16.3/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java#L671-L678).
=> [JENKINS-49717] Hide deprecated credentials type

.github/release-drafter.yml, CHANGELOG.md
See [usage](https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc#usage). I have enabled the app on the repo. If you merge this, we then need to
* apply appropriate labels (like `bug`) to all PRs merged since 1.16.4
* do the 1.16.5 release
* start using it (first release will need more cleanup, to delete the old entries)
=> Release drafter

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Alternative to #508
* Only override HOME for OpenShift
* Warn in the build if HOME is set to `/` to allow user to fix either docker image or pod template configuration.
=> [JENKINS-42763] Only override HOME if OpenShift

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-yamlMergeStrategy.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/mergeYaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/overrideYaml.groovy
Added a yamlMergeStrategy field to PodTemplate/PodTemplateStep in order
to control how yaml field is handled across inheritance of pod
templates. Defaults to "override" in order to be backward compatible.
=> [JENKINS-58405] Backward compatibility for yaml field merge

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/cascadingDelete.groovy
[JENKINS-58306](https://issues.jenkins-ci.org/browse/JENKINS-58306)
=> [JENKINS-58306] Need to explicitly ask for cascading deletion of agent pod

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/jenkinsSecretHidden.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
[JENKINS-58602](https://issues.jenkins-ci.org/browse/JENKINS-58602)
=> [JENKINS-58602] Hide JENKINS_SECRET from pod manifest

README.md
Hi, 
I went through an exercise finding [this](https://github.com/jenkinsci/kubernetes-plugin/pull/429#issuecomment-489144063) fix to my issue with authentication in EKS and noticed there were notes for other cloud k8s providers in the README and thought it'd be helpful to make note of this caveat as well.
=> Added documentation for running on EKS

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Observed in another PR. There is one failed execution, maybe because the pod clean up is too aggressive.
```
Error Message
Output should contain pid: Executing shell script inside container [busybox] of pod [test-command-execution-w9ddq]
Executing command: "sh" "-c" "cd /tmp; echo pid is \$\$ > test; cat /tmp/test" 
exit
Stacktrace
java.lang.AssertionError: 
Output should contain pid: Executing shell script inside container [busybox] of pod [test-command-execution-w9ddq]
Executing command: "sh" "-c" "cd /tmp; echo pid is \$\$ > test; cat /tmp/test" 
exit
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecoratorTest.testCommandExecution(ContainerExecDecoratorTest.java:156)
at …
```
=> Try to address ContainerExecDecoratorTest#testCommandExecution flakiness

README.md
Support has received complaints from users that the Scripts using `POD_LABEL` are not valid, as their instance was not on the newest Kubernetes Plugin version, and received the error:
`No such property: POD_LABEL for class: groovy.lang.Binding`
=> Update ReadME with `POD_LABEL` disclaimer

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/showRawYamlFalseInherited.groovy
[JENKINS-58574](https://issues.jenkins-ci.org/browse/JENKINS-58574)
=> [JENKINS-58574] Fix inheritance of showRawYaml

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
See [JENKINS-58724](https://issues.jenkins-ci.org/browse/JENKINS-58724)
=> [JENKINS-58724] Update existing logger to display current run

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
The test fails about 20% of the time due to this.
=> [JENKINS-58513] Remove this assertion

pom.xml
Supersedes #543, #536, #509, #492, and #467 so far. For [the rest](https://github.com/jenkinsci/kubernetes-plugin/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Adependencies), the BOM will need to be expanded.
=> Use the BOM for some dependency management

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
The `repeatableHeteroProperty` does not get the field from the `entry` parent tag and results in a NPE when rendering the configure page. The `field` attribute is on both the `entry` and `repeatableHeteroProperty` to render the help correctly. This follows precedent set by other fields like `annotations` on PodTemplate.
fixes JENKINS-58740
=> [JENKINS-58740] add missing pod label field attribute to config.jelly

examples/kaniko-declarative.groovy, examples/kaniko.groovy
It will cause the full dir to be read only and some builds will fail
```
failed to initialize build cache at /root/.cache/go-build: mkdir /root/.cache: read-only file system
```
=> Do not mount the full /root dir from secret with Kaniko

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9_invalid/config.xml
[JENKINS-58767](https://issues.jenkins-ci.org/browse/JENKINS-58767)
=> [JENKINS-58767] Persist yaml fragment in a single string

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9_invalid/config.xml
Backport to 1.15 of https://github.com/jenkinsci/kubernetes-plugin/pull/573
=> [JENKINS-58767] Persist yaml fragment in a single string (backport to 1.15.x)

examples/dind.groovy, examples/dood.groovy
Tested on GKE, and saw something similar running with a Kops cluster on AWS.
Could also experiment with [rootless Docker](https://medium.com/@tonistiigi/experimenting-with-rootless-docker-416c9ad8c0d6).
Note that every build gets a fresh Docker daemon, so there is no local layer cache between builds. This could make builds slower, though it also means builds are more deterministic and there is no need for a GC system. I have not experimented with using a `PersistentVolumeClaim` to retain the daemon storage across builds. Probably better to set up a local registry in the cluster as a proxy, just like we would advise for Maven dependencies and the like.
=> Adding a DinD example

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_17_2/config.xml
[JENKINS-58766](https://issues.jenkins-ci.org/browse/JENKINS-58766)
Existing static container templates using workingDir = '/home/jenkins' are migrated automatically to '/home/jenkins/agent'.
=> [JENKINS-58766] Fix migration compatibility for working dir

pom.xml
To get the fix in https://github.com/fabric8io/kubernetes-client/pull/1669
Origin header is set with port -1 when no port is present in the Kubernetes API url
Causing an error on exec
```
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
```
=> [JENKINS-59000] Upgrade kubernetes-client to 4.4.2

pom.xml
See announcement from @oleg-nenashev on the dev list. If merged, we should also delete all real content from Confluence and just say point to GitHub.
=> Switch /project/url from Confluence to GitHub

pom.xml
=> Fix scope for some git plugin transitive dependencies getting pulled as 'compile' instead of 'test'

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/jnlpWorkingDir.groovy
If containers don't specify an explicit working dir, just use the one
specified in jnlp, because if they don't match, the build will fail
anyway.
=> Align working dirs

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/InProvisioning.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/EvictingQueue.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/HostPathVolume.java
Signed-off-by: runzexia <runzexia@yunify.com>
=> clean up unused import & do not import *

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/WorkspaceVolume.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVC.groovy
Signed-off-by: runzexia <runzexia@yunify.com>
Add this kind of workspace volume because during use, we found that some IO-intensive tasks have some problems with the performance of emptyDir.
I want to use dynamic pvc to avoid this performance problem.
When I implemented this part, I found that the original WorkspaceVolume abstract class seems to be only suitable for static PVC.
So I want to find some comments about this part of the code, any comments are very grateful
@Vlatombe @jglick
=> [JENKINS-47591] dynamic pvc workspace volume

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
Evidently unused in this plugin, but can cause problems in downstream plugins.
Note that `PodTemplateUtils.combine(PodTemplate, PodTemplate)` also has a similar long enumeration of fields, and could well be missing some, though this seems to have better test coverage.
=> PodTemplate’s copy constructor was incomplete

kind.sh
#618 failed with
```
docker: Error response from daemon: Invalid container name (jenkins-Plugins-kubernetes-plugin-dependabot%2Fmaven%2Forg.jenkins-ci.plugins-docker-workflow-1.21-1-control-plane), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```
=> Picking a safer name for clusters

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/WorkspaceVolume.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Should fix https://github.com/jenkinsci/kubernetes-plugin/pull/600#issuecomment-543021605
=> Always define an explicit workspace volume, it defaults to an empty dir

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
When KubernetesCloud.directConnection is used and no Jenkins URL is configured (e.g. because Jenkinsfile Runner does not expose an http port -> no Jenkins URL) the following Exception is thrown:
```
java.lang.IllegalStateException: Jenkins URL for Kubernetes is null
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.getJenkinsUrlOrDie(KubernetesCloud.java:330)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.start(PodTemplateStepExecution.java:119)
```
This Pull Request fixes the behavior.
=> Fixed "IllegalStateException: Jenkins URL null" in PodTemplateStepExecution

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
Allows to merge yaml with inherited templates like this:
```
pipeline {
agent {
kubernetes {
inheritFrom "test-template"
yamlMergeStrategy merge()
yaml """
apiVersion: v1
kind: Pod
spec:
containers:
- name: maven
image: maven:3.3.9-jdk-8-alpine
command: ['cat']
tty: true
"""
}
}
stages {
stage('Run maven') {
steps {
container('maven') {
sh 'mvn -version'
}
}
}
}
}
```
=> Add support for yamlMergeStrategy in declarative pipelines

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
https://github.com/jenkinsci/kubernetes-plugin/commit/826e8f3160637609132b02e1d2e3a31e735d2404 appears to have lost the "Delete Pod Template" button in Jenkins core 2.190.2 LTS. [This (fairly old) comment](https://groups.google.com/d/msg/jenkinsci-dev/XHvOM5Co2Mk/YLE2xG0QyHAJ) seems to indicate that you usually need to add your own `f:repeatableDeleteButton`  when using `f:repeatableProperty`
=> [JENKINS-60042] Restore delete button to pod template list

test-in-k8s.sh
Noticed in #649 that #616 omitted a subdirectory needed for `-Pconsume-incrementals`.
=> test-in-k8s.sh did not support Incrementals

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-retentionTimeout.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest/minRetentionTimeoutReadResolve/config.xml
I've seen cases where retention timeout was 0 and this caused agents to be removed after a Jenkins instance restart.
=> Ensure retention timeout is always >= 5

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Fixes some flaky tests results such as https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/dependabot%2Fmaven%2Forg.jenkins-ci.plugins-kubernetes-client-api-4.6.4-1/3/tests
Amends #503
=> Only keep logs from agents

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
[JENKINS-60088](https://issues.jenkins-ci.org/browse/JENKINS-60088)
=> [JENKINS-60088] set label "jenkins/label=<label>" instead of "jenkins/<label>=true"

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-connectTimeout.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-readTimeout.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
[JENKINS-60551](https://issues.jenkins-ci.org/browse/JENKINS-60551)
* Default jelly values from java constants
* Apply min values for `readTimeout` (15 sec) and `connectTimeout` (5 sec)
* Add missing `serverCertificate`, `readTimeout` and `capOnlyOnAlivePods` to
copy constructor
=> [JENKINS-60551] Copy constructor test should check all fields

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
The displayName is pretty generic "Kubernetes Pod Template" and isn't very helpful in the log.
=> Log name of pod template instead of generic value

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/podTemplateWithMultipleLabels.groovy
[JENKINS-60537](https://issues.jenkins-ci.org/browse/JENKINS-60537)
Should fix behaviour when using multiple labels on a single pod template.
For a pod template with the labels `label1 label2`, the pod will be labeled `jenkins/label=label1_label2`, since spaces are not allowed in kubernetes labels values.
Amends #666
=> [JENKINS-60537] Sanitize label

kind.sh
https://github.com/kubernetes-sigs/kind/pull/1157 is supposed to be in https://github.com/kubernetes-sigs/kind/releases/tag/v0.7.0 ([announcement](https://twitter.com/BenTheElder/status/1216906151473733634)) so let us try it!
=> Use enhanced PV support in Kind 0.7.0

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
It was failing because in the kind test environment, it can take more than 10
seconds for the process to complete due to the parallel threads due to
resource constraints.
Split from #686
=> Fix ContainerExecDecoratorTest#testCommandExecution

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/cascadingDelete.groovy
Nothing interesting should be running in agents containers when it is requested to be terminated, so don't wait these 30 seconds to kill remaining processes inside it.
Should speed up a lot tests hopefully.
Subsumes #689 and #690, please review [this](https://github.com/jenkinsci/kubernetes-plugin/pull/686/commits/e5faa7f39ad15fe8acfdbbf691b9b6b10bb478e9) commit.
=> Remove containers grace period

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Flaking [in master](https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/master/673/testReport/junit/org.csanchez.jenkins.plugins.kubernetes.pipeline/ContainerExecDecoratorTest/kind___testCommandExecution/) and on PRs. Probably some issue with failure to flush a stream or something: some, but not all, threads print their output.
=> Suppressing testCommandExecution as too flaky

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
Rename DEFAULT_ID to DEFAULT_LABEL and set value to "slave-default"
=> [JENKINS-60937] Pods are not created due to 'invalid label value: "jenkins/slave-default"'

kind.sh, kind.yaml, test-in-k8s.yaml
Required for testing inside some clusters.
=> Allow test-in-k8s.sh to be used when PodSecurityPolicy is enabled

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
[JENKINS-60798](https://issues.jenkins-ci.org/browse/JENKINS-60798)
=> [JENKINS-60798] Fix kubectl buildwrapper (2nd round)

pom.xml
It seems these are no longer necessary.
=> Remove versions overrides from dependency management

test-in-k8s.sh, test-in-k8s.yaml
Hoping this will fix occasional test failures caused by an inability to rebind 8000.
=> Randomize ports used by test-in-k8s

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Not sure if you consider this an improvement or not. Mainly relevant during tests. Replaces long, basically unreadable single-line messages with long, readable multiline messages.
=> Use Serialization.asYaml when printing API resources to log

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
It is causing issues to people who really want to keep the old value.
[JENKINS-60977](https://issues.jenkins-ci.org/browse/JENKINS-60977)
=> [JENKINS-60977] Drop the working dir migration

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamples.java
Amends #707 to avoid errors when `workflow-cps` is not enabled. Noticed in startup logs of CloudBees `core-oc`.
=> Make KubernetesSamples extensions optional

README.md, examples/openshift-home-yaml.groovy, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
[JENKINS-60133](https://issues.jenkins-ci.org/browse/JENKINS-60133)
Running in openshift with the default jnlp image (`jenkins/jnlp-slave:4.0.1-1`) will issue the following warning
```
[WARNING] HOME is set to / in the jnlp container. You may encounter troubles when using tools or ssh client. This usually happens if the uid doesnt have any entry in /etc/passwd. Please add a user to your Dockerfile or set the HOME environment variable to a valid directory in the pod template definition.
```
=> [JENKINS-60133] Remove openshift-specific behaviour

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Suggested by @jtnord. If the user has not bothered to set any resource requests or limits on the `jnlp` container, it is wise to offer some reasonable default values. I chose 100m CPU and 256Mi memory based on `kubectl top pod` of a container from a simple build in EKS that was generating a modest amount of log output and consuming somewhat less than these values.
=> Set default cpu & memory requests on the jnlp container

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplateTest.java
@jtnord reported having accidentally pasted text into this field with a leading space and getting hard-to-diagnose `KubernetesClientException`s later. Better to do a basic sanity check right away.
=> Validation for ContainerTemplate.image

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
Amends #497
`org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesDeclarativeAgentTest#declarativeWithNonexistentDockerImageLongLabel` is passing but when the `PodTemplate` was copied the TaskListener reference wasn't kept.
=> Fix copy constructor of PodTemplate to keep TaskListener

pom.xml
* instance-identity scope should be provided
* ssh-credentials 1.18
* fix bundled dependencies that shouldn't be packaged
(https://github.com/jenkinsci/maven-hpi-plugin/pull/140 doesn't cover
all use cases)
=> Fix packaging of unwanted dependencies

pom.xml
Downstream of https://github.com/jenkinsci/docker-workflow-plugin/pull/202 & https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/373. Supersedes https://github.com/jenkinsci/kubernetes-plugin/pull/720 & https://github.com/jenkinsci/kubernetes-plugin/pull/733. This plugin will still depend on `docker-commons` via `kubernetes-credentials`, and for the moment it still has `docker-workflow` in `test` scope via `pipeline-model-definition` as I did not make that an `optional` dep (perhaps I should).
=> [JENKINS-58732] Update pipeline-model-definition & drop explicit dep on docker-workflow

README.md
@jtnord highlighted this. a583b4720a202e720df9ddc0fc5e5d4a79e2c6ff was nearly three years ago. If there are bugs not caught by the likes of https://github.com/jenkinsci/kubernetes-plugin/blob/c77a64d8c7f70d0337302c1d204f51676c408b19/src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java#L168-L187 + https://github.com/jenkinsci/kubernetes-plugin/blob/c77a64d8c7f70d0337302c1d204f51676c408b19/src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestartWithLongSleep.groovy#L10, we will endeavour to fix them.
=> Removing warning about container step

src/main/kubernetes/jenkins.yml
> StatefulSet versions apps/v1beta1 and apps/v1beta2 are deprecated
> - use apps/v1, available since Kubernetes 1.9
=> Change StatefulSet apiVersion

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Useful in CloudBees products where we configure KubernetesCloud
instances within folders where credentials are defined, then pushed to a
different Jenkins instance.
I verified this manually but dunno how to test it.
=> Fill credentials from current context instead of just Jenkins singleton

pom.xml
Following up #661 to switch back to an LTS baseline.
=> jenkins.version=2.222.1

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
When working with openshift, when an http_proxy env var is set in the pod, we have autmatically a  -Dhttp.proxyHost setting in the jenkins jvm hence, it is never null. The jenkins http proxy is bever propagated to the pod template even if we check the option.
I was thinking of adding a special test for openshift (kind of is cloud.isOpenshit) to have a specific behaviour for it, but I am wondering In which case we want to propagate the http proxy only if a proxy is not set the jenkins master, which is kind of contradictory.
=> Ensure http proxy is set when addMasterProxyEnvVars is checked

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
Prevents a null pointer exception when a null is set in the volume mounts collection of a container.
This can happen for instance when a yaml file specifies an empty `volumeMounts` section:
```yaml
containers:
- name: jnlp
image: jenkins/jnlp-slave:alpine
imagePullPolicy: IfNotPresent
volumeMounts:
env:
- name: JAVA_TOOL_OPTIONS
value: -Xmx1G
resources:
limits:
memory: "1Gi"
cpu: "1"
```
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> Prevent NPE when null set in container's volume mounts

kind.sh
cf. https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/master/743/console
```
15:40:12  Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
15:40:12  + trap cleanup EXIT
15:40:12  + kubectl cluster-info
15:40:12  kind.sh: line 25: /home/jenkins/workspace/Plugins_kubernetes-plugin_master@tmp/kubectl: Permission denied
15:40:12  + cleanup
```
=> Looks like in some case of workspace reuse the executable exist but don't have right permission

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodNameTest.java
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names is a bit vague but I found insufficient sanitization here.
=> Handle odd job names that do not match DNS_SUBDOMAIN

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
With the previous implementation, I've seen the agent attempting to
reconnect even before the pod is purged, which cause unnecessary errors
displayed in logs (both agent and master side).
With the following change, the node is only marked as temporary offline
until the pod gets deleted.
=> Don't disconnect before deleting pod

kind.sh
https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0
=> Kind 0.8.0

README.md
Recently I've tried to use multiple containers in my pipeline and faced an issue with `sh` step. Pipeline just hung without printing any messages. I've done a little investigation and found out the reason - it was the `permission denied` error because I was using image with different UID together with default `jnlp` image.
This isn't a bug, but I think it still should be covered.
=> Add steps to debug hanged pipeline sh step into README.md

README.md
With regards to the image change [here](:exclamation: Warning! This image used to be published as jenkinsci/jnlp-slave and jenkins/jnlp-slave. These images are deprecated, use jenkins/inbound-agent.) and per the mailing list [here](https://groups.google.com/forum/#!topic/jenkinsci-dev/oxD-Hd_7l9k), I am starting the corrections to the [README](https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md)
=> Removing docker 'slave' ref.. New image is inbound-agent

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Seems that in some cases `KubernetesLauncher#launch` is being called
concurrently. The launcher is designed to run only once, and cleans up
the node upon failure, so it should never be called by concurrent
threads.
=> Prevent concurrent launches

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
We used to use LimitRange to define default resource limits/requests for the jnlp container but since a couple of release, we have to define the limits/request in each pod templates if we want different values from the hardcoded values. 
This can be an issue as some pipeline stuff can't be executed outside of the JNLP container (like git clone / fetch from the git client) and the limited hardcoded resources make the operations very slow or even fail. See https://issues.jenkins-ci.org/browse/JENKINS-51542 (and also probably https://issues.jenkins-ci.org/browse/JENKINS-30600 as a root cause). See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=560283#c16 for details about performance issue.
This PR adds system properties to let the Jenkins instance be started with specific values instead …
=> Make default JNLP container resource requests/limits overridable

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
While I was investigating some failures to schedule windows pods on GKE. Although this doesn't solve the problem, seems to be a bug on GKE side.
=> Don't emit any securityContext block if there is nothing valuable to put inside.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/nullLabelSupportsRestart.groovy
When using a pod template with null label, after restart the job fails with
```
java.lang.IllegalStateException: Not expecting pod template to be null at this point
at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave.getTemplate(KubernetesSlave.java:91)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.secretsOf(SecretsMasker.java:144)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.get(SecretsMasker.java:122)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.get(SecretsMasker.java:94)
at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:94)
at org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:138)
at …
```
=> Fix template resolution for null label after restart

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
From Microk8s. Compare
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-07T14:04:52Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-1+6f17be3f1fd54a", GitCommit:"6f17be3f1fd54a88681869d1cf8bedd5a2174504", GitTreeState:"clean", BuildDate:"2020-06-23T21:17:52Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```
=> Show Kubernetes version in connection test

src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
When the Kubernetes plugin provisions new pods, there is a delay of up to `hudson.slaves.NodeProvisioner.recurrencePeriod` before the queue is checked and new pods are actually started.
NodeProvisioner has a method `suggestReviewNow` to get around this. I'm not sure about the best way to trigger it, so if there's a better way I'm all for it. For now I'm triggering it with a one-off timer with a delay of 1 second.
From my testing, this results in significantly faster pod provisioning, which makes a big difference in short-running jobs.
=> Suggest NodeProvisioner review after adding new pods

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
The rationale is that the typical command will be wrapped in a script
before being sent to the exec api
This typical command looks like this
```
nohup sh -c ({ while [ -d
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf' -a !
-f
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf/jenkins-result.txt'
]; do touch
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf/jenkins-log.txt';
sleep 3; done } & jsc=durable-cd155196dc95897e8d1241f162c2ceac;
JENKINS_SERVER_COOKIE=$jsc 'sh' -xe
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf/script.sh'
>
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf/jenkins-log.txt'
2>&1; echo $? >
'/home/jenkins/agent/workspace/container-time@tmp/durable-3ac42cdf/jenkins-result.txt.tmp …
```
=> Prevent fragmentation of kube exec calls by bumping the container exec buffer size to 16 kb

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
The help text for the K8s Cloud "Concurrency limit" field says:
> The maximum number of concurrently running agent pods that are permitted in this Kubernetes Cloud.
If set to empty it means no limit. Set to 0 means no pod will ever be started.
I noticed that when set to 0, an unlimited number of pods will be started.
This PR makes it so that when the concurrency limit is 0, no pods are started, as per the help text.
=> Don't provision when concurrency limit is 0

examples/dind.groovy
Supersedes https://github.com/jenkinsci/kubernetes-plugin/pull/829.
As per the comments in https://github.com/jenkinsci/kubernetes-plugin/pull/581#issuecomment-683481580, the environment variable which allows containers to connect over TCP will not work without TLS in future versions of docker.
So the example has been updated to use `/var/run`(/docker.sock) instead of TCP.
Note: `/var/run` is used instead of `/var/run/docker.sock` because `docker.sock` is a file and `emptyDir` is a directory, so if `/docker.sock` is used, the daemon fails to start with an error:
> failed to load listeners: can't create unix socket /var/run/docker.sock: is a directory
=> Update DinD Example

examples/dind.groovy
Since there is no `Dockerfile` in the root of https://github.com/jenkinsci/docker-jnlp-slave.git, we need to point to one to build.
=> Fix DinD Example

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/events.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/podLog.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
#367 added views for `KubernetesComputer`. The backends methods need administer role however the views are not protected. They don't display stacktraces since #430 however, the links shouldn't even be there.
Noting #657 is proposing to require `EXTENDED_READ` only. Will likely be affected by this PR.
=> Fix incorrect permission checks in KubernetesComputer views

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
https://www.jenkins.io/changelog/#v2.238
Add `Agent/ExtendedRead` support for viewing agent configuration, system
information, and logs. ([issue 61206](https://issues.jenkins-ci.org/browse/JENKINS-61206))
=> Handle compatibility with 2.238 introducing Agent/ExtendedRead

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Should fix the flakiness observed [here](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/PR-839/6/tests) and [there](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/PR-844/2/tests).
=> Poll for template availability for a few seconds once the pipeline is ready to run

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
This test is flaky due to random HtmlUnit NPEs which I couldn't find a fix for.
```
java.lang.RuntimeException: Could not retrieve XPath >//input[lower-case(@type)='radio' and @name='tab-group-1600698390637']< on HtmlPage(http://localhost:30656/jenkins/)@1301124704
at com.gargoylesoftware.htmlunit.html.xpath.XPathHelper.getByXPath(XPathHelper.java:93)
at com.gargoylesoftware.htmlunit.html.DomNode.getByXPath(DomNode.java:1613)
at com.gargoylesoftware.htmlunit.html.HtmlRadioButtonInput.setCheckedForPage(HtmlRadioButtonInput.java:183)
at com.gargoylesoftware.htmlunit.html.HtmlRadioButtonInput.setChecked(HtmlRadioButtonInput.java:139)
at com.gargoylesoftware.htmlunit.html.HtmlRadioButtonInput.onAddedToPage(HtmlRadioButtonInput.java:292)
at …
```
=> Ignore `KubernetesPipelineTest#computerCantBeConfigured`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Problem introduced in #318: https://github.com/jenkinsci/kubernetes-plugin/pull/318/files#diff-eff844000c9e60765310e70fa8c8a71cL308-L310
=> `PodTemplateUtils#combine` shouldn't have a side-effect on the parent pod template

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
We found that `maxConcurrentRequests` in the K8s Client was always 64 no matter what the above number was set to. 
The config was properly setting `maxConcurrentRequestsPerHost` on the client, but one can still hit the bottleneck described in [JENKINS-58463](https://issues.jenkins-ci.org/browse/JENKINS-58463) after setting it, because testing showed that `maxConcurrentRequests` plays an equal role in limiting the number of concurrent requests allowed.
=> [JENKINS-58463] Allow maxConcurrentRequests to go above 64

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-containerCapStr.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Reverts the logical part of https://github.com/jenkinsci/kubernetes-plugin/pull/828, improves the help text, and amends the test which proves that `0` means unlimited.
I tried hard in https://github.com/jenkinsci/kubernetes-plugin/pull/864 and https://github.com/jenkinsci/kubernetes-plugin/pull/865 to have `0` become "disabled," because that's what made sense to me when https://github.com/jenkinsci/kubernetes-plugin/pull/828 was filed, but for upgradeability reasons `0` must keep its original meaning of "unlimited."
=> Fix: Concurrency limit 0 must mean unlimited for upgradeability

README.md, README_zh.md, examples/dood.groovy, examples/kaniko-declarative.groovy, examples/kaniko-gcr.groovy, examples/kaniko.groovy, examples/openshift-home-yaml.groovy, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_0_12/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_0_8/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_10/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_1/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9_invalid/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_17_2/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVC.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithMultipleContainers.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
As mentioned in https://www.jenkins.io/blog/2020/05/06/docker-agent-image-renaming/ and https://issues.jenkins-ci.org/browse/JENKINS-42846
Additional change old tag version from 3.35-5-alpine to 4.3-4-alpine (like commit 278798c02)
=> Hacktoberfest - Fixup docker image name and tag

README.md
Release 1.26.0 introduced an update [1], which made older versions of Kubernetes
fail rather obscurely, and with them, OpenShift 3 too. The instruction provided
in the issue discussion and release notes might be hard to find for new users
of the plugin, thus adding them to the readme.
As OpenShift 3.11 will still be maintained until June 2022 [2], many
users might be hitting this issue for a while still.
[1] https://github.com/jenkinsci/kubernetes-plugin/pull/790
[2] https://access.redhat.com/support/policy/updates/openshift_noncurrent
=> readme: add instructions for running with OpenShift 3

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
cf. https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#simplifying-with-runtimeclass
=> Don't set nodeSelector when `.spec.runtimeClassName` is set

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
This should be merged using _merge commit_ to retain the release-related commits in the history of `master`.
=> Merge security fixes from 1.27.4 back into master

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
Fixes removal of ephemeral pod templates when they don't specify an explicit `cloudName`
Replaces #878
=> Resolve cloud when removing dynamic template

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
I'm suspecting `KubernetesPipelineTest#podTemplateWithMultipleLabels` to be flaky because of the clock-based provisioning strategy.
=> Add more logs to tests in order to diagnose flakiness

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Some exception I've seen being raised when the calling code already takes into account the template being unresolved
=> fix: getPodRetention throws IllegalArgumentException

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
As per
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#shutdown-isnt-necessary
As the kubernetes client only close the underlying client, and it is not necessary to explicitly close http clients,
it should be safe to leave as is once it is expired.
If some calling code is holding to old instances, they can still use them provided the token-based authentication still works.
Ultimately, this should prevent occurrences such as
```
2020-11-04 06:49:56.143+0000 [id=329776]    WARNING
i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure
java.util.concurrent.RejectedExecutionException: Task
okhttp3.RealCall$AsyncCall@556ba43e rejected from
java.util.concurrent.ThreadPoolExecutor@217680e3[Terminated, pool size =
0, active threads = 0, queued tasks = 0, completed tasks …
```
=> Simplify caching by removing the close logic

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
For security reasons most enterprises mandates all docker image pulls are proxied through enterprise docker registry. Prior to this change, only possible mechanism will be to set the entire image with proxy prefix as system property. Though it works, it comes with huge maintenance overhead as the property value needs to be frequently changed to use newer version of inbound agents. This change allows to set the docker registry prefix once and inherit the default JNLP image defined in the ode.
- Fixes [JENKINS-61931](https://issues.jenkins-ci.org/browse/JENKINS-61931).
- Added ability to set docker registry prefix for default JNLP image using System Property
Looks like its not possible to test this change via unit tests, hence tested locally to ensure the changes work.
=> [JENKINS-61931] Add ability to set docker registry prefix for default JNLP image

pom.xml, src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
I've noticed the NodeProvisioner is not triggered immediately when a new item enters the queue so we can probably make it faster.
=> Add a QueueListener triggering node provisioning

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/MetricNames.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/MetricNamesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Amends #872 since I don't have write access to the source branch.
=> Pr 872 follow-up

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/MetricNames.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/MetricNamesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
This PR is to add some basic dropwizard metrics to track status of provisioned pods.
I migrated Jenkins instances from Mesos to Kubernetes recently and noticed that the kube plugin doesn't provide metrics related to builder nodes provisioning like the [mesos plugin does](https://github.com/jenkinsci/mesos-plugin/blob/mesos-0.18.1/src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java#L412).
These metrics become useful at scale when the number of Jenkins instance is quite big and they help to spot issues with Jenkins -> cloud provider as early as possible.
I took the same approach as the mesos plugin and use [dropwizard metrics](https://metrics.dropwizard.io/4.1.2/) (and [the metrics plugin](https://plugins.jenkins.io/metrics/)), however, I personally not a big fan of them as they don't …
=> Add dropwizard metrics to track status of pods

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithDifferentShell.groovy
Reverting #771 because it turns out that this was actually testing something useful: that the build fails promptly if you specify the wrong `shell` for a `container` step. The behavior as of then was not great (`IOException: Pipe closed` rather than the more helpful `no such file or directory` it emitted at one point) but after #757 it is much worse: the `sh` step simply hangs. CC @ccojocar
=> Resurrecting KubernetesPipelineTest.runInPodWithDifferentShell

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
`v1.17.13-gke.2001` is more informative than `1.17+`.
=> testConnection should display gitVersion rather than major.minor

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
This allows to specify jnlp container limits through system properties.
`org.csanchez.jenkins.plugins.kubernetes.PodTemplateStepExecution.defaultContainer.defaultMemoryLimit`
`org.csanchez.jenkins.plugins.kubernetes.PodTemplateStepExecution.defaultContainer.defaultCpuLimit`
Sometime need to set limits for jnlp.
Otherwise, we get an error
=> Specify jnlp container limits through system properties

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/octalPermissions.groovy
This brings support for octal numbers for fields specified through the `yaml` field.
=> Update jackson2-api to 2.12.0

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-instanceCap.html
According to this fix (https://github.com/jenkinsci/kubernetes-plugin/commit/a3227ae0df8310edfe2fbb4273d68ca7e6191678) the inline help should include zero (0) with the ranges of values which means no limits
=> Adding zero as "no limit value" for cap

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
A change introduced in v1.27.1 (https://github.com/jenkinsci/kubernetes-plugin/pull/825) meant that queued build tasks will be canceled and terminated with failure if Kubernetes returns 4xx error.
This change prevents failing the build if a resourcequota is exceeded or in conflict. Instead, the queued item will continuously retry scheduling until successful or aborted.
This is useful in envs which use resourcequotas and want the pod to eventually schedule when some resource is free. Additionally on some kubernetes clusters a 409 response may be returned if many pods are scheduled in a short amount of time (typically parallel jobs), a immediate retry typically resolve this.
Related ticket: JENKINS-63976
=> [JENKINS-63976] Avoid canceling build if resourcequota exceeded or conflict

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
[JENKINS-61072](https://issues.jenkins.io/browse/JENKINS-61072)
Init containers were not covered by the existing merge logic.
=> [JENKINS-61072] Merge init containers

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
[JENKINS-62502](https://issues.jenkins.io/browse/JENKINS-62502)
=> [JENKINS-62502] `ContainerExecDecorator` should escape double quotes

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Reverts jenkinsci/kubernetes-plugin#924
Caused [JENKINS-64675](https://issues.jenkins.io/browse/JENKINS-62502), breaking windows nodes
=> [JENKINS-64675] Revert "[JENKINS-62502] `ContainerExecDecorator` should escape double quotes"

README.md
This took me a couple of hours to figure out, as I tried to use every single alternative to prevent extending the container. Sadly, this is the only way to do as it seems that a solution like https://github.com/jenkinsci/docker-inbound-agent/pull/38 is not going to get implemented.
=> Add additional configuration guide for websockets

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Based on #961
* `labelSet` and `labelMap` are now updated every time `label` is updated.
* Jenkins indexes `Label` instances on creation. Since the `Cloud` doesn't offer a `getLabels` method, this is the only way to provide intel to Jenkins that labels can be satisfied.
=> Create labels on pod template creation

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Double quotes need to be escaped with `\` only on unix environments.
When running on windows, escaping isn't the same (not sure whether there is even a problem), so leave it untouched.
=> [JENKINS-62502] Escaping double quotes, take 2

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Following some issues reported in https://github.com/jenkinsci/kubernetes-plugin/pull/939, I noticed some calls to `Jenkins.get().removeNode(...)` which were not caught, and actually a better way is probably to listen directly to deletion events.
=> Limits: fix some cases where unregistration doesn't happen

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
I have a small cluster with nodes of varying capabilities where a custom scheduler is required. I'm able to set the `spec.schedulerName` field in my Jenkinsfile however the value is ignored (verified by checking the resultant YAML contents in the Jenkins logs). I've also tried adding the field to the pod template raw YAML config but this also seemed to be ignored.
This change will read the scheduler name field, if supplied, and add it to the final YAML output.
=> feat: Allow override of scheduler name spec field

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/inheritFrom.groovy
Pod events streaming is not happening when using inheritance because the listener is not copied to the combined pod template.
=> [JENKINS-65415] Map listener on inheritance

README.md
add default value for command & args, command is `sleep`, and args default value is `99999999`.
=> add default value for command & args in README document

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
100 seconds is too low to handle pulling windows images which can be very large (~10G). Also helps those with slow network.
=> Increase default connection timeout to 1000 seconds.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
I've hit some issue while executing tests - the problem was that `java.net.URI` was not parsing the `host` part for some urls like:
```
URI u3 = URI.create("http://asd-7.1-asd:15002");
System.out.println(u3.getHost()); // this will be null
```
the issue was that there is a special check in the URI parser - which requires that the last uri part must start with an alpha
https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/net/URI.java#L3395
This caused an issue because I left the name of the `podTemplate` empty - and let the plugin name the pods ; and since I had a version number in the job name this have sparked the above issue.
Tracking down this was hard; but fixing it is easy - also mask dots with underscores; as it is done for other chars.
=> Mask dots in generated pod names

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
This pr uses linked hashmap so that the containers can be started in the order specified by the template. This is useful in scenarios where backing services needs to be started first.
=> Use linked hashmap to keep container order as defined in pod template

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
This is just a stupid idea to make upgrades to Java 11 smoother in the default case: When Jenkins itself is running with Java 11, select a Java-11-based default image, so the Java version between controller and agents matches.
=> Use jdk11 agent when Jenkins is running on jdk11

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
This reverts commit 4fac91e0c94c5529d4dcc7f65cab78bec0b6f7d7, reversing
changes made to cb6008f0c072706925e89951ad82bc4358362e2e.
We now depend on core 2.263.1 which has
https://github.com/jenkinsci/jenkins/pull/4730
=> Revert "Merge pull request #781 from Vlatombe/runInPod-flake"

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimitsTest.java
This change provides a more sound concurrent code rather than double locking on `AtomicInteger` + `SynchronizedMap`. The class now relied on internal locking mechanism and ensure that `#init` method is properly synchronized as well. 
I was not able to reproduce the issue described in [JENKINS-66484](https://issues.jenkins.io/browse/JENKINS-66484) but at least this code does not break it either.
Talking about unit tests, I decreased the number of clouds and templates in order to raise the possibility of a race condition. I also ensured that `#register` and `#unregister` are all called from separate threads. Finally, I replaced the `if` checking the return value of `#register` by a `while`, as we want to test all the cases.
JIRA: https://issues.jenkins.io/browse/JENKINS-66484
=> JENKINS-66484 - Tentative fix of a race condition in KubernetesProvisioningLimits

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
[JENKINS-63847](https://issues.jenkins.io/browse/JENKINS-63847)
Regression probably caused by #757. Before, it always used `\n`, which seemed to work on Windows.
Under `PrintStream`, `BufferedWriter` captures current line separator on initialization, and this behaviour can't be tuned.
This avoid using `println` and uses an eol character depending on the agent OS.
=> [JENKINS-63847] Use line separator from agent OS instead of master OS

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
This fixes an exception raised when a node fails to launch, but without any suppressed exception to log.
While the exception is raised in an already-failing case, it was also preventing proper handling of that failure (notably, the subsequent call to `node.terminate()` would not happen), which would leave the affected node in a bad state.
Example of a stack trace where this issue is encountered:
```
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
Also:   java.lang.Throwable: launched here
at hudson.slaves.SlaveComputer._connect(SlaveComputer.java:282)
at hudson.model.Computer.connect(Computer.java:440)
at hudson.slaves.CloudRetentionStrategy.start(CloudRetentionStrategy.java:73)
at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy.start(Once …
```
=> Fixes an ArrayOutOfBoundException on node launch failure

src/main/kubernetes/jenkins.yml
Make ingress compatible with K8s v1.22 (expects minimum v1.19 now)
[kubernetes deprecationguide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)
=> Make ingress compatible with K8s v1.22 (expects minimum v1.19 now)

src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
`mvn test -Djenkins.version=2.309 -Dtest=PodTemplateJenkinsTest#jenkinsLabels` is failing with
```
[ERROR] org.csanchez.jenkins.plugins.kubernetes.PodTemplateJenkinsTest.jenkinsLabels  Time elapsed: 7.243 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: iterable with items ["master", "foo", "bar"] in any order
but: not matched: "built-in"
```
This is because of terminology changes in Jenkins Core. I am keep the previous "master" and new "built-in" to have it work on both previous Jenkins 2.309 and after.
=> Fixing test: Labels have been updated from master to built-in

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
The use of Jenkins Proxy configuration was made conditional but the flag
was not added to the connection test. As a result, users who require
a proxy would always get the connection error.
Jelly view and `doTestConnection` handler were updated to include the
flag.
I only confirmed by looking through requests in the Network tab of Web Developer tools. Not sure if this can be tested automatically.
=> Ensure "Use Jenkins Proxy" is honored in Connection Test

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
I'm seeing occasional flakes where 137 is returned instead of 143 and vice versa. What matters is that it gets logged here.
=> Relax terminated exit code - can be 137 (SIGKILL) or 143 (SIGTERM)

README.md
This causes users to think that the Kubernetes extension might be faulty. A couple of Jira issues were opened about it, but none gained traction towards a fix though.
The referenced issue collects information about all the others, and describes a possible workaround for now.
References https://issues.jenkins.io/browse/JENKINS-67062
=> Add note about resuming builds not working with WebSockets

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
Amends #991
I've seen in https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-plugin/detail/PR-1068/2/tests/
```
java.lang.AssertionError: expected:<10> but was:<3>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.csanchez.jenkins.plugins.kubernetes.PodTemplateMapTest.concurrentAdds(PodTemplateMapTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
=> Each pod template instance should operate on its own message digest

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Can be enabled in the build console starting Jenkins with
`-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.verbose=true`
or
```
org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.VERBOSE=true
```
in the groovy console.
=> [JENKINS-64628] Add some diagnostics logging when registering/re-registering pod templates through DSL

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/terminatedPod.groovy
[JENKINS-67160](https://issues.jenkins.io/browse/JENKINS-67160)
=> [JENKINS-67160] Don't fail if not able to retrieve container logs when the pod is terminated

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
[JENKINS-67196](https://issues.jenkins.io/browse/JENKINS-67196)
Amends #1050 
Partially revert f95a6044, as it was not honoring long timeouts anymore.
=> [JENKINS-67196] Pods are terminated after ~110s and ignore PodTemplate.connectionTimeout when containers start

pom.xml
Bringing https://github.com/jenkinsci/kubernetes-client-api-plugin/releases/tag/5.10.1-171.vaa0774fb8c20 in kubernetes plugin.
=> Bump fabric8 to 5.10.1 and bump with latest release of kubernetes-client-api

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, test-in-k8s.yaml
Noticed a local test failure from #1083 that seems unrelated. In #544 I ensured that the test will not fail on CI due to lack of permissions, but if instead of
```bash
TEST=KubernetesPipelineTest\#cascadingDelete bash test-in-k8s.sh 
```
you are running locally with e.g.
```bash
mvn test -Dtest=KubernetesPipelineTest\#cascadingDelete -DconnectorHost=10.1.37.1 -Djenkins.host.address=10.1.37.1
```
without `serviceaccount/jenkins` it could also fail.
=> Prevent `KubernetesPipelineTest.cascadingDelete` from spuriously failing locally

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Just some dead code cleanup. Introduced in #497 then rendered unused in #772.
=> Removing unused `AllContainersRunningPodWatcher.runListener`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
**Description:**
When a non Kubernetes node is provisioned inside the container clause the steps executions fail because it is trying to cast a DumbSlave to KubernetesSlave - https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java#L255. I added a check and if the node is not an instance of KubernetesSlave it just returns the original launcher.
**JIRA Link:** https://issues.jenkins.io/browse/JENKINS-66986
_No upstream or downstream changes._
**Before change**
**After change**
=> [JENKINS-66986] Allow non kubernetes nodes to be provisioned inside the container clause

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYamlWithNullEnv.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-jnlp-nullenv.yaml
This may happen if `env` is explicitly set to null in the container spec.
A pipeline snippet triggering this:
```groovy
pipeline {
agent {
kubernetes {
yaml """\
spec:
containers:
- name: builder
image: alpine:3.15
imagePullPolicy: Always
env:
""".stripIndent()
defaultContainer 'builder'
}
}
// ...
}
```
A stack trace copied from a failed build that triggered this:
```
java.lang.NullPointerException
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.secretsOf(SecretsMasker.java:129)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.get(SecretsMasker.java:101)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.SecretsMasker$Factory.get(SecretsMasker.java:73)
at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:9 …
```
=> Avoid NPE if container environment is null

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
https://issues.jenkins.io/browse/JENKINS-64628
Similar to #1045. #1095 may fix root cause, but there are liable to be race conditions here anyway, so best to behave defensively.
=> [JENKINS-64628] Avoid ISE from `KubernetesSlave.getTemplate` in `SecretsMasker`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
Extracted from #1083. Deprecated and unused since #512.
=> Removing unused `ContainerExecDecorator.ws`

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
=> Removing comment about `Reaper` rendered incorrect by #714

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Noticed in #1083 and worked around there by calling `setupHost` again after restart. Amends #616 in a sense.
=> `KubernetesTestUtil.setupHost` should call `KubernetesCloud.setJenkinsUrl` not `JenkinsLocationConfiguration.setUrl`

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Extracted from #1083. https://github.com/jenkinsci/kubernetes-plugin/pull/786#issuecomment-989131043
=> `KubernetesPipelineTest.containerTerminated` sometimes fails to print `Reason: OOMKilled`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/invalidImageGetsCancelled.groovy
When launching an agent before any kubernetes agent has ever come online, reaper should be initialized so that it can handle events like unable to pull image, etc.
=> Initialize reaper when launching a kubernetes agent

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorWindowsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamplesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/basicWindows.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/interruptedPodWindows.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/secretMaskingWindows.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/windowsContainer.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/windowsRestart.groovy
When using the `container` step on windows containers, build wrappers are not receiving the expected output compared to the equivalent on linux systems.
There are multiple issues:
* The windows welcome message displayed when running the initial `cmd.exe` in the container
```
Microsoft Windows [Version 10.0.17763.2686]
(c) 2018 Microsoft Corporation. All rights reserved.
C:\>
```
* The input stream itself, now disabled using `cmd.exe /Q`
* The input echo from sending commands. This gets disabled by calling `@echo off` before anything else.
* I also found out that the quoting applied for linux commands can mess with windows commands, especially when it is a builtin command such as `echo`. Not sure whether this is the proper way to deal with it though.
I didn't find any way to disable the …
=> `container` step: Fix issues with build wrappers on Windows

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithCreateContainerError.groovy
Signed-off-by: Mor Cohen <mocohen@redhat.com>
**Description:** 
When creating a pod with a miss configured container, its state becomes `CreateContainerError`, and for some reason (probably because `kubernetes-client`) the pipeline enters to an endless loop that creates pods until the pipeline is stopped (aborted/pipeline timeout/etc.. but not by a timeout set by this plugin.). 
Currently, the plugin knows how to handle errors like `ImagePullBackOff` state or when one of the containers are terminated, but not when the pod's state is `CreateContainerError`.
**Jira ticket:** 
https://issues.jenkins.io/browse/JENKINS-66822
=> Cancel Queue Items for Pod - `TerminateAgentOnContainerTerminated ` Listener

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineOverridenNamespaceTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
This allows `PodDecorator` instances to have access to the full pod specification when decorating it.
Updated existing tests to ensure that.
=> Make sure namespace is set explicitly in the pod metadata when set either through the cloud or the pod template

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesQueueTaskDispatcher.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesQueueTaskDispatcherTest.java
Fix for restricting pipeline support to authorised folders. Functionality seems to be partly implemented.
Use case is to be able to on a folder level restrict which folder that can use which Kubernetes cloud.
Jira Issue:
https://issues.jenkins.io/browse/JENKINS-56687
=> JENKINS-56687: Restrict pipeline support to authorised folders fix

pom.xml
Does not appear to be necessary; the only time that the instance identity is used directly by this plugin is in direct connect mode for TCP agents, but even then we get the public key from core anyway: https://github.com/jenkinsci/kubernetes-plugin/blob/44fee1844a33a5946bf9f721edb9da64b7b7b3da/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java#L436
See https://github.com/jenkinsci/jenkins/pull/6585. Supersedes #1183.
=> Remove `instance-identity` dep

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderPropertyTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesQueueTaskDispatcherTest.java
kubernetesFolderProperty/permittedClouds used a "non-standard" way of setting property up, so it needed to have the folder saved before applying it (Configure -> Save -> Configure).
With this change cloud list is provided by the `Descriptorimpl` having all the clouds available regardless the instance of the property hasn't been created yet.
Also, clouds in the form were being treated as `JSONObject` map entries (`usage-permission-<cloud-name>` --> `true | false`), so this object was treated in `reconfigure` to generate a `Set<String>` with the permitted clouds, this has been changed to follow a simpler approach, with a `permittedClouds` entry containing the list of cloud names now (`permittedClouds` --> `["cloudA", "cloudB", ...]`).
Migration is not needed, as the saved object is the same …
=> Allow kubernetesFolderProperty/permittedClouds to be setup without saving

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/StandardPlannedNodeBuilder.java
=> [JENKINS-68371] Avoid unwrapping pod template multiple times when once is enough

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Looks like removing the queue item can kill the thread (?) so the
logging wasn't performed as expected
=> Fix `KubernetesPipelineTest#errorPod` flakiness

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProviderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcherTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
Update Reaper to keep track of watchers across multiple clouds and add/remove
them when clouds are updated. To better track when watchers need to be
recreated the KubernetesClientProvider#getValidity method was made public.
This allows the Reaper to validate the watch client connection is still valid if
the cloud connection properties are updated.
If a watcher is closed due to "410 Gone" responses the watcher will deregister
itself and reregister next time a node comes online.
Watcher implementations will now filter out Bookmark and Error action events
which don't represent Pod state changes. Future enhancement might be to use
bookmarks on reconnect to catchup on events.
Deprecated KubernetesLauncher `watcher` field which does not appear to be
used by the plugin anywhere and is a …
=> Update Reaper watchers across multiple clouds and config updates

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-jnlpregistry.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
In case a Jenkins does not have the ability to pull from DockerHub but instead there is a DockerHub mirror available this should be used for the default JNLP image that will be in every pod that has not specified a JNLP image.
The reason why only the registry should be configured instead of the entire image path is that this way the plugin still decides which is the correct image to use and the configuration only defines where this image should come from.
=> Make Docker registry for JNLP image configurable

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeRetries.groovy
Follows up #1190. Split from #1083. Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/533.
=> [JENKINS-49707] `retries` option for `agent kubernetes`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
Extracted from a test PR: https://github.com/jenkinsci/kubernetes-plugin/pull/1211#discussion_r922242669
=> Robustness of `SecretsMasker` looking up `KubernetesComputer`

README.md
The plugin requires specific kubernetes Role assignments to work correctly if running under a custom ServiceAccount
I am not particular about the title/wording of the documentation, but it could have saved me some time to have this information in the documentation.
=> Document necessary k8s Role rules for plugin

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
When running with `mvn clean verify -Djenkins.version=2.357`, I noticed these errors:
```
[ERROR] src/jenkinsci/kubernetes-plugin/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java:[419,32] error: as of release 9, '_' is a keyword, and may not be used as an identifier
[ERROR] src/jenkinsci/kubernetes-plugin/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java:[482,28] error: as of release 9, '_' is a keyword, and may not be used as an identifier
```
After this PR I can no longer reproduce the problem.
=> Plugin cannot compile with Java 11

Jenkinsfile
Some builds are reaching the 60 minutes timeout (https://github.com/jenkinsci/kubernetes-plugin/pull/1233 / https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/PR-1233/1/display/redirect)
=> Increase kind stage timeout to 90 minutes.

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud/config.jelly
Noticed while investigating a customer issue with a LOT of these.
=> Display the cloud name for non-configurable kubernetes clouds to help distinguish between multiple instances.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
Untested and not sure if the problem was reproducible. Browsed to the configuration screen of a multibranch project and saw in the logs
```
WARNING	h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: descriptor.effectivePermissions in /job/multibranch/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.NullPointerException
at org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty$DescriptorImpl.getEffectivePermissions(KubernetesFolderProperty.java:218)
```
Fix from source inspection: this is an `AbstractFolderProperty` available on `ComputedFolder`s, so it should not presume that it can find a (non-computed) `Folder` in its ancestor list.
Amends #1181 by @PereBueno.
=> `KubernetesFolderProperty` threw NPE on a `WorkflowMultiBranchProject`

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorConditionTest.java
Seems to have been dead code since it was introduced by @jglick in #1190.
=> Remove dead code

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly
The change proposed replaces the spinner.gif animation with the drop-in replacement provided by `<l:progressAnimation>`:
**Before**:
https://user-images.githubusercontent.com/13383509/194014960-9f32b808-7142-4d4e-be17-b7bb932b468d.mp4
**After**:
https://user-images.githubusercontent.com/13383509/194015157-be85bc4b-1dc8-4eb6-b83b-c97c5cd4d5e9.mp4
=> Replace old spinner.gif with modern animation

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/events.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/podLog.jelly
The change proposed utilized the modernized `jenkins-table` design, rather than the old table design.
**Before**:
**After**:
=> Use modernized jenkins-table design

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/terminatedPodAfterRestart.groovy
Follows up #1190. Split from #1083. Downstream of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180.
=> [JENKINS-49707] Test `retry(…, conditions: [kubernetesAgent()])` across restarts

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecutionTest.java
If I'm executing `mvn clean install` on my local machine, everything works fine but the build fails in our jenkins pipeline. The `PodTemplateStepExecutionTest` runs into a timeout because the jenkins could not started. After visiting other test classes, I realized that each kubernetes cluster specific test class extends from `AbstractKubernetesPipelineTest` which provides a `JenkinsRuleNonLocalhost` instance. The `PodTemplateStepExecutionTest` class does **not** extends from `AbstractKubernetesPipelineTest` but also provides a `JenkinsRuleNonLocalhost` instance. That seemed really strange to me, so I changed `JenkinsRuleNonLocalhost` to `JenkinsRule` in `PodTemplateStepExecutionTest` (see my committed file). After pushing to our repository, I started the jenkins pipeline build again and …
=> Fix PodTemplateStepExecutionTest in jenkins pipeline build

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Similar to #1096 etc. An observed stack trace indicates some problem but it should be handled more gracefully:
```
WARNING	o.c.j.p.k.p.r.Reaper$CloudPodWatcher#lambda$eventReceived$0: Listener org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnContainerTerminated@… failed for …
java.lang.IllegalStateException: Unable to resolve pod template from id=…
at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave.getTemplate(KubernetesSlave.java:91)
at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$TerminateAgentOnContainerTerminated.onEvent(Reaper.java:408)
at org.csanchez.jenkins.plugins.kubernetes.pod.retention.Reaper$CloudPodWatcher.lambda$eventReceived$0(Reaper.java:318)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at …
```
=> Prefer `getTemplateOrNull` to `getTemplate`

examples/dind.groovy
This is simple fix to "dind" example, which when run returns error as `docker version `executes before docker daemon is up in another container.
The change will now execute simple loop to ensure daemon is up and only then execute `docker version`.
=> wait for docker daemon to start in dind example to avoid error

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Not sure what the problem was exactly, but the error handling itself was broken when `getCloud` returned null:
```
WARNING	jenkins.util.Listeners#lambda$notify$0
java.lang.NullPointerException
at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave.getKubernetesCloud(KubernetesSlave.java:237)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave.getKubernetesCloud(KubernetesSlave.java:229)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesProvisioningLimits$NodeListenerImpl.onDeleted(KubernetesProvisioningLimits.java:146)
at jenkins.model.NodeListener.lambda$fireOnDeleted$2(NodeListener.java:85)
at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
at jenkins.util.Listeners.notify(Listeners.java:70)
at jenkins.model.NodeListener.fireOnDeleted(NodeListener.java:85)
at …
```
=> NPE from `KubernetesSlave.getKubernetesCloud`

README.md
=> [JENKINS-49707] Document pod retries

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/WithContextClassLoader.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Updated the last occurrence to `DefaultKubernetesClient` that should be done with a context classloader swap.
The last occurrence under `KubernetesTestUtil` is in test scope so not affected (flat classloader)
=> [JENKINS-70392] Compatibility fix with kubernetes-client 6.x (again)

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamples.java
Despite #715, I once again started to see errors from CloudBees `core-oc` about this class. (Perhaps due to a different class linking strategy in recent JVMs? I cannot think what else of significance would have changed.) I tried to reproduce using `RealJenkinsRule.omitPlugins("workflow-cps")` without success. Reproduced interactively in `core-oc.war` with a snapshot build of `kubernetes.hpi` and verified this fix.
=> Trying again to make `KubernetesSamples` optional

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
This can cause two clouds with identical configuration except for name to be mistaken.
=> `Cloud.name` should be part of `equals/hashCode`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-serverCertificate.html
This improves overall usability when trying to connect to a remote EKS cluster.
=> Add support for `serverCertificate` base64-encoded, such as what is provided by Amazon EKS

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Related: https://github.com/fabric8io/kubernetes-client/pull/4528
`TokenRefreshInterceptor` in kubernetes-client refreshes the kubernetes client configuration every minute.
When using a "secret text" credentials in Jenkins, the client is initialized with the given token. However upon refresh, it applies autoconfiguration from injected paths such as `/var/run/secrets/kubernetes.io/serviceaccount/token` and so discards the initial token.
https://github.com/fabric8io/kubernetes-client/pull/4528 fixed the problem when providing the full kubeconfig file through a "secret file" credentials.
The remaining problem in kubernetes-client has been filed upstream https://github.com/fabric8io/kubernetes-client/issues/4802
This PR disables autoconfiguration when both a kubernetes URL and credentials are …
=> [JENKINS-70493] Disable Kubernetes client autoconfiguration when an URL is provided

Jenkinsfile, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Always.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Default.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Never.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/OnFailure.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetention.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetentionTest.java
Not tested yet, but hoping this would avoid
```
java.net.SocketTimeoutException: connect timed out
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at …
at java.base/java.net.Socket.connect(Socket.java:609)
at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
at …
Caused: java.io.IOException: connect timed out
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:533)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:570)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:482)
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:742)
at …
```
=> Do not ask API server for a `Pod` during deletion unnecessarily

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
The next Jenkins core LTS based on 2.387 has changed how "advanced" buttons are rendered. This is fixing tests so they pass for both 2.387 and also older versions.
cf. https://github.com/jenkinsci/jenkins/commit/f81a7c121d81adca87b7d141634c4bda80351755
=> Fix tests for the upcoming LTS

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-inheritFrom.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-name.html
The help message of the PodTemplate `name`  attribute is wrongly suggesting that the name defaults to the `label`. This isn't true. 
* In the context of a `podTemplate(...)` step execution, a name would be automatically generated and use the `label` as a prefix.
* In other contexts, by default the pod and node created are prefixed with `jenkins-agent-`. As per https://github.com/jenkinsci/kubernetes-plugin/blob/d5b1bcbc89dec3fbcbcc5a49e32bbc9a63ed74a8/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java#L71.
Also improved the `inheritFrom` help that the name of a template must be provided (and not a label)
=> Improve PodTemplate name and inheritFrom help messages

pom.xml
15 seconds look too short for CI -- https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/019404b3832a42a312766384d437162bcb93aeed/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java#LL95C84-L95C166
=> Give more time to agent to reconnect after a restart in CI

pom.xml
From https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/179
Upgrade kubernetes-client-api to use okhttp-api plugin instead of embedding the client.
This also indirectly upgrades okhttp to 4.x, but it is binary compatible with okhttp 3.x and it fixes a compatibility issue with ipv6.
=> Upgrade kubernetes-client-api to 6.4.1-215.v2ed17097a_8e9

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorConditionTest.java
Amending #1190. Sometimes a `node` block can fail with e.g. `AgentOfflineException` yet this is not `retry`d and it is not obvious why. Was OOMKiller active, for example?
=> Send diag to build log when `KubernetesAgentErrorCondition` does not match

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
[JENKINS-70416](https://issues.jenkins.io/browse/JENKINS-70416)
Whenever authentication is provided in the Kubernetes plugin, we do not want to be impacted by the automatic Config refresh mechanism (like the token refresh for example) of the fabric8/kubernetes-client: https://github.com/fabric8io/kubernetes-client/blob/v6.4.1/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L637-L651. We might however still want to use the autoconfigure when initializing the `ConfigBuilder` object if configuring a Kubernetes Cloud in the same cluster but in a different namespace or with a different auth.
Fix the token refresh problem in a multi-namespaced / same cluster scenario. Where different serviceaccount (with token) are used in other namespaces and a Secret Text …
=> [JENKINS-70416] Ensure auto-configure is disabled when auth is provided

Dockerfile, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
Update KubernetesComputer side panel icons to Jenkins design library symbols.
Includes a fix for Dockerfile build to include required plugin dependencies.
=> Jenkins design library symbols

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
This PR remove the duplicated help button around "Workspace Volume" present in "Manage Jenkins" > "Configure Cloud" > "Kubernetes" > "Pod Templates" > "Pod Template details"
Before:
After:
=> Remove duplicated help button around Workspace Volume in Pod Template details

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
With #1335 in use, I hit this on a K8s build recently
```
org-repo-main-230-5fwds-qbqzj-sfdzs was not a Kubernetes agent judging by [org_repo_main_230-5fwds]
```
Turns out the script had been using
```groovy
retry(count: 2, conditions: [kubernetesAgent(), nonresumable()]) {
podTemplate {
node(POD_LABEL) {
// …
}
}
}
```
which does not work since at the point that `retry` is asked whether to rerun its block, the only information it has about the agent was that `POD_LABEL`, which has already been deleted from the ephemeral pod template registry (the agent definition itself was probably deleted at the end of the `node` block). I suppose it could match on `/.+-[a-z0-9]{5}/` but this pattern might be used by other cloud plugins as well. Best to just swap the order of the steps, as the …
=> Clarify in warning message why `retry` might have declined to do so

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
https://github.com/jenkinsci/kubernetes-plugin/pull/1344#issuecomment-1500616868
Could cause some inappropriate retries of pipelines that were broken for a good reason (misconfiguration), but that is probably tolerable here in exchange for better robustness when an agent pod fails to connect for a transient reason.
Did not figure out how to write an automated test for this. Manually verified that
```diff
diff --git src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
index 8e794195..1096add3 100644
--- src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
+++ src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
@@ -419,7 +419,7 @@ public …
```
=> Activate `KubernetesAgentErrorCondition` when `podTemplate {node {…}}` fails to connect

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineOverridenNamespaceTest.java
Several years ago, Jenkins core switched from the abandoned JSR 305 annotations to SpotBugs annotations, but this plugin never caught up. This PR adapts this plugin to the common convention used in Jenkins core and the vast majority of other Jenkins plugins.
=> EOL JSR 305

README.md, src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
Add system property `io.jenkins.plugins.kubernetes.NoDelayProvisionerStrategy.disableCloudShuffle` to disable randomizing the cloud list. When disabled  clouds are search in the order they are defined making for more predicable pod template selection.
The use case for disabling is for multi-cloud environments where templates in both clouds share common labels and predictable cloud and pod template selection is desired. For example the first cloud is preferred and the second cloud is a backup, say for when the instance cap is hit.
Tested in live environment
```[tasklist]
```
=> feat: system property to disable no delay provisioner cloud shuffle

src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
When CloudProvisioningListener returns a blockage cause it should continue on to the next cloud.
```[tasklist]
```
=> Fix no delay provisioner search

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
While checking why #1415 did not automatically deploy, I saw that the trunk commit failed with a [flake in `KubernetesPipelineTest.errorPod`](https://github.com/jenkinsci/kubernetes-plugin/runs/15878427431)
```
Expected: a string containing "jnlp -- terminated (1)"
but: was "Started
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Created Pod: kubernetes kubernetes-plugin-test/error-pod-1-rpsj1-z7xj2-7nnm8
kubernetes-plugin-test/error-pod-1-rpsj1-z7xj2-7nnm8 Container jnlp was terminated (Exit Code: 1, Reason: Error)
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
Queue task was cancelled
org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 65b59291-4c40-4b7c-925a-ea0448f6dbcc
Finished: ABORTED
"
```
I found that …
=> `KubernetesPipelineTest.errorPod` flake revealed bug in `Reaper`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
As I understand it, this caused `KubernetesSlave#nodeProperties` to be `null`  after a restart instead of returning an empty list.
Could not reproduce it via `RestartPipelineTest` maybe because `RestartableJenkinsRule` is not realistic.
```[tasklist]
```
=> `KubernetesSlave#readResolve` should call super implementation

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java
After changes introduced in https://github.com/jenkinsci/kubernetes-plugin/pull/1260 we have frequent error with `NullPointerException`. Based on a [documentation][2] for `watch.exitCode` method it's clear that watch.exitCode() can return null if close is received before the exit code. In such a case, you can handle the null value and provide an appropriate default or error value.
```
java.lang.NullPointerException at
org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecProc.join(ContainerExecProc.java:89)
at hudson.Proc.joinWithTimeout(Proc.java:174)
at com.cloudbees.jenkins.plugins.sshagent.exec.ExecRemoteAgent.stop(ExecRemoteAgent.java:129)
```
Fix for JENKINS-71135
[2]: https://github.com/fabric8io/kubernetes-client/blob/8a879128d893627a40d64cf2a9c7d5da2e7f47d2/kubernetes-clie …
=> Handle the case when `watch.exitCode` may return null

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/DirectConnectionTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/directConnectionAgent.groovy, test-in-k8s.sh
@dduportal reported a regression in the latest Remoting images, which I was able to confirm as a regression in https://github.com/jenkinsci/remoting/pull/677 (exact cause still unknown):
```
kubernetes-plugin-test/direct-connection-agent-1-dbxfx-1c3pg-jndq9 Container jnlp was terminated (Exit Code: 1, Reason: Error)
- jnlp -- terminated (1)
-----Logs-------------
Oct 23, 2023 12:57:35 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Oct 23, 2023 12:57:35 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
Exception in thread "main" java.io.EOFException: unexpected stream termination
at …
```
=> Added `DirectConnectionTest`, downgrading agent image

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
https://issues.jenkins.io/browse/JENKINS-72314
Roundtrip test was bogus so it didn't catch the regression introduced by #1443
Also fixed a few setters causing incorrect `KubernetesCloud` equality.
```[tasklist]
```
=> [JENKINS-72314] Fix cloud save and roundtrip test

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Amends https://github.com/jenkinsci/kubernetes-plugin/pull/1471 taking into account https://github.com/jenkinsci/kubernetes-plugin/pull/1471#discussion_r1395848295
```[tasklist]
```
=> [JENKINS-72314] Tidy up previous changes

src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVC.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
follows https://github.com/fabric8io/kubernetes-client/pull/2178 to use proper background cascading deletion preventing clients that cannot have access to finalizer to fail to create a pvc
This PR comes after hours of researching an issue on openshift https://access.redhat.com/solutions/4577161
the fabric8io dependancy changed the default cascading deletion to "background" 3 years ago.
In https://kubernetes.io/docs/concepts/architecture/garbage-collection/#cascading-deletion , we can see that blockOwnerDeletion=true is only used in foreground cascading deletion
But setting blockOwnerDeletion=true cause an issue with restricted Openshift environments where the serviceaccount cannot have access to finalizers
Setting it to false should default to use proper background cascading deletion
As …
=> Use background cascading deletion of DynamicPVC

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/configuration-as-code.yaml
https://issues.jenkins.io/browse/JENKINS-70217
When defining a container template using Casc and unspecified command and arg, it seems more natural that the default entrypoint and args are executed. So setting these to empty string when constructing a new instance seems more natural.
This doesn't change the behaviour of creating a new container template using the UI, as the default value will come from jelly because the ContainerTemplate instance will be null when populating the jelly fragment.
Flagged as a bug because in the previous state, both fields were left to `null` when unspecified by casc, and the UI roundtrip would replace them by `sleep` and `999999`, due to the default jelly attribute.
```[tasklist]
```
=> [JENKINS-70217] Default ContainerTemplate command and arg to empty string when using casc.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
[JENKINS-72441](https://issues.jenkins.io/browse/JENKINS-72441)
As per https://github.com/jenkinsci/kubernetes-plugin/pull/1392#discussion_r1389995902
Remove the `synchronized` - that was added to fix a spotbug warning - causing lock contention on accessors. And use an AtomicBoolean instead to make spotbugs happy.
**Testing agent low to launch**
* Create a pipeline:
```
pipeline {
agent none
stages {
stage('Hello') {
steps {
podTemplate(envVars: [envVar(key: 'JENKINS_TUNNEL', value: ':50999')]) {
node(POD_LABEL) {
// some block
sh "echo 'Hello World'"
}
}
}
}
}
}
```
* Run it
* Follow the link to the agent created from the console out
* Validate that the agent page is accessible
**Testing normal launch**
* Create a pipeline:
```
pipeline {
agent none
stages {
stage('Hello') {
steps { …
```
=> [JENKINS-72441] Prevent lock contention on `KubernetesLauncher#isLaunchSupported`

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/containerEnvironmentIsHonored.groovy
=> Test and document environment inside `container` step with current shortcomings

pom.xml
Now that the baseline is available in LTS form, prefer it for the reasons given in [the documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).
=> Require 2.426.1 LTS or newer

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentRJRTest.java
https://github.com/jenkinsci/workflow-cps-plugin/pull/538#issuecomment-1883256755 not successful yet despite
```diff
diff --git pom.xml pom.xml
index df3627bc..f95064a8 100644
--- pom.xml
+++ pom.xml
@@ -134,6 +134,7 @@
<dependency>
<groupId>org.jenkins-ci.plugins.workflow</groupId>
<artifactId>workflow-cps</artifactId>
+      <version>3832.vc43e04d6d68c</version>
<optional>true</optional>
</dependency>
<dependency>
```
but it seems appropriate to at least have _some_ test coverage here.
=> Introduce `KubernetesDeclarativeAgentRJRTest`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest/decimal.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest/octal.yaml
**Context**
Kubernetes-client uses jackson-databind to parse yaml into objects, using snakeyaml. 
Kubernetes-client has migrated their serialization methods to use SnakeYAML engine (https://github.com/fabric8io/kubernetes-client/pull/4836)
The problem is that snakeyaml uses yaml 1.1 while snakeyaml-engine only supports yaml 1.2.
This causes inconsistencies when dealing with integer with the octal notation, as there are breaking changes between these two versions. Additionally, https://github.com/FasterXML/jackson-dataformats-text/issues/3 documents that octal notation is not properly supported through jackson.
**Plugin perspective**
This follows up https://github.com/jenkinsci/kubernetes-plugin/pull/1342, already providing some octal notation conversion.
User yaml is still expected to use …
=> [JENKINS-71956] Octal notation fixes

pom.xml
Picks up https://github.com/jenkinsci/kubernetes-client-api-plugin/releases/tag/6.10.0-240.v57880ce8b_0b_2
Necessary because apparently kubernetes-client broke binary compatibility (https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/247#issuecomment-1914301522) even though no source change is required in the plugin.
Closes #1505
```[tasklist]
```
=> Update kubernetes-client api to 6.10.0

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
Failure reproduced with
```
Index: src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
--- a/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java	(revision a81cd9f202d95012f5918d3f496e7c2b5ac87703)
+++ b/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java	(date 1709649329339)
@@ -198,6 +198,11 @@
// close any cloud watchers that have been removed …
```
=> Fix flake on `ReaperTest#testRemoveWatchWhenCloudRemoved`

pom.xml
We depend on mock libraries part of kubernetes-client or okhttp3, and these need to be kept in sync with the main library.
This adds enforcer executions that will fail the build if these start diverging.
```[tasklist]
```
=> Enforce consistent versions for mock libraries

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateGroup.java
While recently working on downstream consumers of `PodTemplateGroup`, I noticed that there is a not actually a `PodTemplateGroup#addTemplate`, though there is a `KubernetesCloud#addTemplate`... I think that it make more sense that this method be declared in `PodTemplateGroup`.
```[tasklist]
```
=> Add `PodTemplateGroup#addTemplate`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-inheritYamlMergeStrategy.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/configuration-as-code.yaml
Ticket: https://issues.jenkins.io/browse/JENKINS-72112
**This Pull Request is taken from https://github.com/jenkinsci/kubernetes-plugin/pull/1448 and the changes done there!**
I was not quite sure what the workflow in such cases is, I could also open a PR on the fork so that the first forker can update the PR here, I just assumed it is simpler this way.
Testing done in https://github.com/jenkinsci/kubernetes-plugin/pull/1448, I am fixing (at least I try ;-) ) the automated tests that prevent it from merging.
```[tasklist]
```
=> [JENKINS-72112] Allow merge strategy inheritance in PodTemplates

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
The issue is described in detail here - https://issues.jenkins.io/browse/JENKINS-72886
This PR adds checks for empty Lists because `args` and `command` fields are initialized as empty lists by default, and they can't be `null`. Before this change `args` and `command` from parent template were overridden with empty values, because `null` check always returned `false`. 
After this change `args` and `command` fields will be preserved from parent template if child don't provide any. This is the expected behavior.
I've added simple unit test which failed before this change and now passes successfully. It check that fields from parent container template are present if child template doesn't contain these fields  
```[tasklist]
```
=> [JENKINS-72886] fix `command` & `args` are lost when combining container templates

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Now that `KubernetesCloud` has its own configuration page, it is no longer necessary to hide its configuration by default.
To be reviewed [ignoring whitespaces](https://github.com/jenkinsci/kubernetes-plugin/pull/1541/files?w=1).
```[tasklist]
```
=> Unwrap advanced configuration section

src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
See https://github.com/jenkinsci/jenkins-test-harness/pull/764. `MIME_TYPES` just has `text/javascript`, which is already the default in Jetty anyway, so this does nothing. Simpler to remove this field eventually rather than to try and adapt it for Jetty 12 calling conventions. This PR gets us closer to being able to remove it.
CI build
=> Remove reference to `MIME_TYPES`

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Follows up #1089, #1474, #1480
PVCs and pods can take some time to terminate, so let's just wait a bit more
```[tasklist]
```
=> Better test robustness

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
https://github.com/jenkinsci/docker-agent/pull/809 added support for `REMOTING_OPTS` in order to pass custom remoting options to the agent.
This makes use of the new option to pass `--noReconnectAfter 1d`, allowing the agent to bail out after 1 day of not being able to contact the controller.
This can be tweaked using `-Dorg.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.noReconnectAfter=30d` using the syntax allowed by the agent per https://github.com/jenkinsci/remoting/pull/738
Tested using `mvn hpi:run -Dorg.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.noReconnectAfter=1m`, launching a kubernetes agent, then turning off the controller. The agent bails out after 1 minute in that case.
```[tasklist]
```
=> Add `--noReconnectAfter 1d` option when available in the agent image.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Could happen if somehow `PodTemplateStepExecution#onResume` doesn't run after a restart, or if the pipeline run gets deleted and the agent still exists ?
In such a case, the agent will attempt to connect forever but won't be able to resolve a pod template reference.
I've seen the case on a real instance but I don't know how to reproduce it though.
=> Handle case where a node is launched with an invalid template

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineWebsocketRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/AssertBuildLogMessage.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/CreateWorkflowJobThenScheduleTask.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/restartDuringPodLaunch.groovy, test-in-k8s.yaml
See [JENKINS-73224](https://issues.jenkins.io/browse/JENKINS-73224) for details.
Easier to review hiding whitespace changes: https://github.com/jenkinsci/kubernetes-plugin/pull/1561/files?w=1
Automated test added.
=> [JENKINS-73224] Do not try to create a pod which already exists

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
`KubernetesLauncher` is a `Describable` but as it is only instantiated programmatically. Not having a matching `Descriptor` class is not a problem for daily operations in the plugin, but some code may request for `computer.launcher.descriptor` and produce walls of exceptions for no good use.
=> Add a dummy descriptor for `KubernetesLauncher`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecoratorException.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/decoratorFailure.groovy
Only handles dynamic pod templates, not static pod templates.
=> Handle Pod decorator failure by aborting the pending queue item.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityContextInjector.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/AbstractGoldenFileTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/existingSecurityContext-after.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/existingSecurityContext-before.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/multiContainer-after.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/multiContainer-before.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/simple-after.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/simple-before.yaml
When `restrictedPssSecurityContext = true` in a kubernetes cloud, all created containers will be augmented with a security context compatible with "restricted" Pod Security Admission.
If a security context individual field has been manually set earlier, this won't be overridden. In such case, the pod will be rejected and the user should correct its pod definition.
=> Apply restricted PSS to all containers when enabled

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
https://issues.jenkins.io/browse/JENKINS-73276
The fix is to not allow user without admin permission to save empty form.
Manually tested using steps from the Jira.
=> [JENKINS-73276] do not allow user without admin permission to save empty form

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/declarative.groovy, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/maven.groovy
Update examples to be runnable as is when the namespace it runs in is configured with "restricted" PSA.
This assumes that in such a case the option `restrictedPssSecurityContext` at kubernetes cloud level is set to `true`, as it injects automatically part of the required security context for such workload.
=> Update linux samples for PSA "restricted"

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
See https://github.com/jenkinsci/kubernetes-plugin/pull/1560#issuecomment-2196805834 for details
I saw some cases where some container in pods return completed status even when eviction api used
```
[14:14:36.964+02:00] - *******-m5g2b Containers flux,jf,jnlp,kubedock,maven,oc were terminated. Pod was evicted by the Kubernetes Eviction API.
```
```
[14:14:37.130+02:00] - - flux -- terminated (137)
[14:14:37.130+02:00] - -----Logs-------------
[14:14:37.130+02:00] - - jf -- terminated (137)
[14:14:37.130+02:00] - -----Logs-------------
[14:14:37.130+02:00] - - jnlp -- terminated (143)
[14:14:37.130+02:00] - -----Logs-------------
[14:14:37.130+02:00] - - kubedock -- terminated (0)
[14:14:37.130+02:00] - -----Logs-------------
[14:14:37.130+02:00] - - maven -- terminated (137) …
```
=> Ensure retry if `EvictionByEvictionAPI` is found on termination reasons

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
`activeDeadlineSeconds` in `combine` for template Pods was ignored, parent value always use in combined Pod. 
```plain
Aug 04, 2024 3:53:41 PM FINEST org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils
Combining pods, parent: ---
apiVersion: "v1"
kind: "Pod"
metadata: {}
spec:
activeDeadlineSeconds: 1800
containers:
...
template: ---
apiVersion: "v1"
kind: "Pod"
metadata: {}
spec:
activeDeadlineSeconds: 43200
containers:
...
Aug 04, 2024 3:53:41 PM FINEST org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils
Pods combined: ---
apiVersion: "v1"
kind: "Pod"
metadata: {}
spec:
activeDeadlineSeconds: 1800
containers:
...
```
I have added a case where the child value overrides the parent value. And the case when the template inherits the parent value.
=> fix(PodTemplateUtils): override parent activeDeadlineSeconds by child value if not null

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/MetricNames.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/MetricNamesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
See https://issues.jenkins.io/browse/JENKINS-73788 for details
Compiled+unittested the plugin.
Installed to local Jenkins without issues.
Small scale test indicates that the troublesome metrics are no longer collected. I can roll this out to a larger Jenkins instance for more thorough (live) testing, but that will have to wait for our maintenance window.
=> [JENKINS-73788] Reduce metrics bloat relating to provisioning requests

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest/nonCompliantCloudsAreCleanedTest/config.xml
https://issues.jenkins.io/browse/JENKINS-73789
This change updates the FIPS check, so now empty certificates are accepted. Certificates using an invalid key algorithm / size will still be rejected.
Added a new cloud creation in existing test with no certificate and checked it's created.
=> [JENKINS-73789] empty certificate is valid now

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest.java
Following https://github.com/jenkinsci/kubernetes-plugin/pull/746. Using the context is useful in CloudBees plugin that allow managing Kubernetes Cloud within folders.
cc @Vlatombe @jglick 
* Tested creation of new cloud under **Manage Jenkins > Cloud**
* Tested configuration of new cloud under **Manage Jenkins > Cloud**
* Tested creation of new Kubernetes Shared Cloud in a folder (CloudBees instance)
* Tested configuration of new Kubernetes Shared Cloud in a folder (CloudBees instance)
=> Use current context for validation functions

README.md, README_zh.md, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-image.html
Repo https://github.com/jenkinsci/docker-inbound-agent has been archived on Jan 22, 2024.  Its content is now included in https://github.com/jenkinsci/docker-agent/.
=> Update source code url for docker-inbound-agent

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
I was previously using an ECR Pull Through Cache for the `inbound-agent` image, but this wasn't respected when using `agentInjection: true`. This PR fixes that
Added a unit test, and tested on my own Jenkins instance - expected behaviour present
=> Use configured registry for jenkins-agent when running in agent-injection mode

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
I ran a disaster recover scenario where a controller started in a fresh cluster with no record of old `Pod`s. Of course the agent used by a running build did not reattach, but then the log printed
```
Ignored termination reason(s) for …-f8fp6-qkfpk-htdxt for purposes of retry: []
```
and did not retry the stage. In this scenario we do not expect there to be any recorded termination reasons, so we _do_ want to retry. I suspect this is a regression from #1582.
([CloudBees-internal reference](https://cloudbees.atlassian.net/browse/BEE-53208))
=> `KubernetesAgentErrorCondition` failed to handle DR

src/main/java/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityContextInjector.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/AbstractGoldenFileTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/agentInjection-after.yaml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/RestrictedPssSecurityInjectorTest/agentInjection-before.yaml
When using both `agentInjection: true` and the checkbox "Inject restricted PSS security context in agent container definition" in an environment using restricted PSS, then the resulting pod can't be scheduled because the init container doesn't have the proper security context set.
This modifies the existing PSS logic to decorate as well init containers.
=> Make Restricted PSS security context work together with agent injection

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/maven.groovy
[JENKINS-74950 - Improve the K8s Maven sample to run in resources limited environments](https://issues.jenkins.io/browse/JENKINS-74950)
The sample "kubernetes-maven.groovy" does not specify any  request or limit.
In resource limited environments it could fail due to OOM events.
We have reproduced this issue by running it in a pod with memoty limited to 256Mi.
We have modified the current sample to add requests and limits for memory.
```
spec:
containers:
- resources:
requests:
memory: "256Mi"
limits:
memory: "512Mi" 
```
Manual test have been performed to confirm the script works properly in limited environments that was failing with the original sample.
=> JENKINS-74950 - Improve the K8s Maven sample to run in resources limited environments

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/watch/PodStatusEventHandler.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodProvisioningStatusLogsTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/containerStatusErrorLogs.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/podStatusErrorLogs.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/podStatusNoErrorLogs.groovy
[JENKINS-74992](https://issues.jenkins.io/browse/JENKINS-74992)
=> [JENKINS-74992] Print relevant pod provisioning events in build logs

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/watch/PodStatusEventHandler.java
I found out when working on a CloudBees proprietary feature that `KubernetesCloud#readResolve` is not always called on deserialization. I think this will not happen in OSS, but let's stay on the safe side and initialize the field before using it.
Following up https://github.com/jenkinsci/kubernetes-plugin/pull/1627
=> [JENKINS-74992] Avoid NPE on informers

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-instanceCap.html
https://github.com/jenkinsci/kubernetes-plugin/pull/919 updated the help text for a PodTemplate's instanceCap to indicate that '0' is an unlimited value. In practice, while '0' does act as unlimited for the **cloud** containerCap, it really means "zero instances" for a pod template.
The PodTemplate treatment of a 0 instanceCap is determined by [PodTemplate.setInstanceCap](https://github.com/jenkinsci/kubernetes-plugin/blob/8b0d329ed8ec4e30bb5540553bf279541ee4bcba/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java#L377-L384), where we only get `Integer.MAX_VALUE if instanceCap < 0`. To make things extra confusing, this is different from the [same setter for the podTemplate pipeline step](https://github.com/jenkinsci/kubernetes-plugin/blob/8b0d329ed8ec4e30bb5540553bf27954 …
=> Improve accuracy of PodTemplate's instance cap help-text

pom.xml, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
Depends on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/762.
=> Avoid excessive `Closure`s

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Start Jenkins with `-Dorg.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.disableDiagnosticLogs=true` to disable diagnostic pod provisioning in build logs.
=> Option to disable diagnostic pod provisioning in build logs

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodUtilsTest.java
Extract pod name generation functions to PodUtils for better testability and
reusability.
> This pull request is part of a series of small changes and enhancements to support a new plugin to add ephemeral container support to Kubernetes agents. This feature was originally built as an enhancement to this plugin and has been running in live production environment for a few years. CloudBees engineers suggested we create a new plugin rather than contribute here. https://github.com/jenkinsci/kubernetes-plugin/compare/master...cronik:kubernetes-plugin:feature/ephemeral-containers
Added unit tests and have been running in production environment for a few years.
=> Extract pod name generation functions

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Minor enhancement to Reaper to improve debugging of Pod failures. In many cases the TaskListener returned by the slave is a NULL instance so the pod last lines are not visible. This change makes these logs available as "FINE" system logs.
=> Print pod last lines to system logs on failure

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Was removed from main through parent pom, but was still present in tests through casc test-harness.
Excluding until we pick up https://github.com/jenkinsci/configuration-as-code-plugin/pull/2683
=> Exclude jetbrains annotations from tests

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
This change delegates `PodTemplateBuilder` command line split functions to a new `PodTemplateUtils#splitCommandLine` function. This new function improves command line quote handling, including support for single quotes.
This new function was moved to `PodTemplateUtils` so it is in the same class as `substituteEnv`, which it depends on, and so it can be used extensions that might need to build a fabric8 model from a `ContainerTemplate`.
=> Refactor ContainerTemplate command split function

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesNodeContext.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesNodeContextTest.java
Refactor `KubernetesNodeContext` to make it public for extensions to make use of `ContainerExecDecorator`. This refactor introduces a new method `getPodResource()` to get access to the associated `PodResource` from the client. This reduces the need for direct access to `KubernetesClient` and the `connectToCloud()` method.
=> Make KubernetesNodeContext public

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Evicted.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-podRetention.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-podRetention.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Messages.properties, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetentionTest.java
Add retention strategy on pod eviction
I'm interested by keeping only agent pods that were evicted by kubelet (to monitor their ephemeral storage).
mvn clean install and implemented some tests.
Evicted pod have a reason set to 'Evicted' such as
```yaml
status:
....
message: 'The node was low on resource: ephemeral-storage. Threshold quantity: 19245089737,
available: 16938436Ki. Container **** was using 2719916Ki, request is
0, has larger consumption of ephemeral-storage. '
phase: Failed
podIP: ****
podIPs:
- ip: ****
qosClass: Burstable
reason: Evicted
startTime: "2025-06-26T09:16:33Z"
....
```
=> Add retention strategy on pod eviction

README.md
Adjusting #1593 instructions to actually work for Windows-based tests, since Windows K8s DNS does not allow partial suffixes. Needed for #1724 / #1726.
=> Fixing `jenkins.host.address` instructions

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
See [JENKINS-75827](https://issues.jenkins.io/browse/JENKINS-75827)
In some cases, there are deadlock on KubernetesProvisioningLimits during initialization.
The solution we have applied to mitigate this deadlock has been to remove the use of raw hashMap + synchronized methods to ConcurrentHashMap objects and remove the synchronized in the initInstance methods.
We have needed to maintain some synchronized logic on the register/unregister, as this is counting real time the number of instances per cloud/podTemplate, and this will fail if there is no sync enabled, but the nested sync from register/unregister and initInstance has been removed.
We have tried to reproduce the issue with and without these changes, and we have not been able to reproduce it in any case, but at least it seems the …
=> [JENKINS-75827] - Deadlock on KubernetesProvisioningLimits during initialization

src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_invalidCredentials.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_missingCredentials.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/cascadingDelete.groovy
`bitnami` images are gone, switch to another set that is currently maintained.
=> Update kubectl image to a maintained one

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java, src/test/resources/kubeconfig
[JENKINS-76157](https://issues.jenkins.io/browse/JENKINS-76157)
Since https://github.com/fabric8io/kubernetes-client/pull/6153, the behavior described to not use autoconfigure ONLY IF there is no auth provided is not respected anymore. If one specifies the Kubernetes URL `https://kubernetes.default.svc.cluster.local/` the client is not autoconfigured and use to the `default` namespace.
* adding tests that would have passed with Kubernetes client api < 6.13.2
* set autoconfigure when auth is null
* Spin up Jenkins in Kubernetes in a namespace other than default
* Configure a Kubernetes Cloud and set the Kubernetes URL to https://kubernetes.default.svc.cluster.local/
* Try to provision a Kubernetes agent using the cloud
=> [JENKINS-76157] Restore autoconfigure when auth is not null

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
[JENKINS-76095](https://issues.jenkins.io/browse/JENKINS-76095)
Cleanup resources linked to expired clients.
Expired clients may leak threads overtime under certain conditions (simplest reproducible is when a client credentials are not working anymore and the client is used over and over). Proposing to use a `java.lang.ref.Cleaner` to "schedule" the closure of the client when the references are GCed.
Hopefully this is good enough. A more aggressive way would be to schedule for closure based on number of active connections I guess. I recall that we were doing that in the past..
* Start Jenkins with `org.csanchez.jenkins.plugins.kubernetes.clients.cacheExpiration=1` to stress this out
* Spin Up Jenkins
* Configure a Kubernetes Cloud with a fake credentials ( credentials that doe snot work …
=> [JENKINS-76095] Schedule cleanup of expired clients
