pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave/configure-entries.jelly
Latest docker-plugin introduced incompatible changes
+ fix some version conflicts in dependencies
@reviewbybees
=> Fix version conflicts

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
=> [JENKINS-29254] Use fabric8 as Kubernetes client library

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
=> Instance cap is set to 0 when form field is empty

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
=> Fix NPE if credentials are not provided and work correctly if server cert is empty

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-args.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-command.html
Only image is actually required, use @DataBoundSetters
Use a default remoteFs if not set
=> Pod template command was renamed to arguments in API v1

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodVolumes.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/HostPathVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/HostPathVolume/help-hostPath.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/HostPathVolume/help-mountPath.html
=> Add support for hostPath volumes.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodVolumes.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/EmptyDirVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/EmptyDirVolume/help-memory.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/EmptyDirVolume/help-mountPath.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/SecretVolume/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/SecretVolume/help-mountPath.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodVolumes/SecretVolume/help-secretName.html
This PR adds two additional pod volume types:
- secret
- empty dir
=> Add support for secrets and empty dir volumes.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
Add checkbox to select imagePullPolicy for container
=> Image pull policy checkbox

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-resourceLimitCpu.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-resourceLimitMemory.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-resourceRequestCpu.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-resourceRequestMemory.html
This is a quick pass at adding resource request and limits to new containers.
=> JENKINS-33346 - Add resouce request and limit to container

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
This will ease the identification in kubernetes of pods created by jenkins.
=> Generate Cloud Slaves node base on pod template name

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
This has been discussed as part of #59.
=> #59: Allow blank namespace and reuse whatever is discovered by the client.

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerEnvVar.java
Not sure if this is the best way to do it, however works for me.
Updated README with more info on container config too
=> Add support for containerEnvVar's in pipelines

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
https://issues.jenkins-ci.org/browse/JENKINS-37087
=> [JENKINS-37087] Handle multiple labels correctly

README.md
Fixed the comma in the code  which was an issue.
=> Fixed the comma in the sample code

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java
Fixes Unauthorized message from OpenShift API
=> [JENKINS-39867] Upgrade fabric8 to 1.4.26

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
The cloud is not set and they can't be deleted anymore
=> Fix NPE when slaves are read from disk

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep/config.jelly
This PR gets the configuration defined in the Cloud settings to the Kubernetes Client used in the ContainerStep.
=> Instantiating Kubernetes Client with proper config in Container Steps

pom.xml
This is the latest kubernetes-client version, which uses the latest kubernetes-model version. The latest kubernetes-model has all resources implement Serializable, which is a big deal when it comes to pipelines.
=> Upgrade to the latest kubernetes-client version.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodImagePullSecret.java
=> [JENKINS-40457] java.lang.ArrayStoreException when a image pull secret is defined

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
Fixes deletion of containers in pod templates, property is databound
=> Fixes delete containers in pod templates, property is databound

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Fixes #104
Use the cloud defined in podTemplate step
Remove deprecations in step and step execution classes
=> container step always uses cloud named 'kubernetes'

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
Possibly caused due to empty envVars in container template after an upgrade
https://issues.jenkins-ci.org/browse/JENKINS-41725
=> [JENKINS-41725] NPE in PodTemplateUtils.combine

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
https://issues.jenkins-ci.org/browse/JENKINS-41847
=> [JENKINS-41847] NPE in addProvisionedSlave when label is null

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
Listen in all interfaces for minikube tests
Print more log lines on agent errors
=> [JENKINS-42315] Make PodTemplate optional within pipeline

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe/help-execArgs.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
* Show liveness probe settings in the advanced area
* Add help text for the liveness probe command
* Remove form validation for execArgs
=> Show liveness probe settings in the advanced area

README.md
Unless we should be reading this in Sean Connery's voice?
=> Fix small spelling mistake

pom.xml
When pod is not accepted due to quotas the error is misleading
https://issues.jenkins-ci.org/browse/JENKINS-44189
=> [JENKINS-44189] Upgrade kubernetes client

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runDirContext.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestart.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runJobWithSpaces.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenNamespace.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenNamespace2.groovy
Using -Dkubernetes.context=mycontext
Default to minikube
=> Run tests against any configured kubernetes cluster

README.md, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Of course open to suggestions for a better property name :-).
=> manually specify test host address if automatic discovery fails

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Otherwise tests will error out if no Kubernetes cluster is available.
=> Assume that Kubernetes server is reachable

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithExistingPodSimpleEnvVariable.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithExistingTemplate.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVars.groovy
Add tests
Rewrite test secrets creation using SecretsBuilder
=> Allow passing envVars to podTemplate

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Token credentials may expire after some time and need to reconnect
Changes to configuration were not applied after the client was created
=> [JENKINS-39867] Do not cache kubernetes connection

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Linked to this issue:
https://issues.jenkins-ci.org/browse/JENKINS-46433
=> Add podAnnotations to combined pod template

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ProvisioningCallback.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Allows to read the url from the system property or
environment variable KUBERNETES_JENKINS_URL.
=> Implement a method returning the Jenkins URL to use.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
I don't know if that has any unforeseen consequences, I just made a quick test.
@iocanel: did you have any specific reasons to request a tty?
=> [JENKINS-46087] do not use a tty to prevent nohup.out from being created

Jenkinsfile-kubernetes, README.md, pom.xml, src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
=> Do not listen in all interfaces, just minikube one

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java, src/test/resources/kubenamespace
=> Namespace is erroneously autodetected as 'default'

Jenkinsfile-kubernetes, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Based on branch name and build number
=> Use unique labels for each test

pom.xml
=> Fix SCM URL so that PCT can checkout

pom.xml
=> Configure POM repositories over HTTPs

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ServiceAccountCredential.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_1/credentials.xml
Allow using StringCredentialsImpl as tokens
Move ServiceAccountCredential to kubernetes-credentials
With changes from https://github.com/jenkinsci/kubernetes-credentials-plugin/pull/2
=> Use kubernetes-credentials 0.3.0

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
=> [JENKINS-48959] Add labels to log message when cap is reached

README.md
Hi I noticed the old documentation had missing brack and body parameter. I ended up playing around and getting my implementation working quite nicely - thought it'd be worth updating the documentation.
=> Improved usage of podTemplate documentation

README.md
to avoid conflicting pod templates
https://issues.jenkins-ci.org/browse/JENKINS-47759
=> [JENKINS-47759] Use unique labels in examples

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
@carlossg I mixed up during my previous rebase and I forgot to update this.
=> [JENKINS-47501] Avoid overprovisioning, missing commit 

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Fixes [JENKINS-50134](https://issues.jenkins-ci.org/browse/JENKINS-50134).
=> KubernetesCloud: copy jenkinsTunnel in copy ctor

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-yaml.html
=> Fix inline help formatting for yaml option

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Add tests for labels
Needs #325
=> [JENKINS-51137] Merge labels from yaml

pom.xml
This adds the test jar to packaging.
I'm building a plugin depending on kubernetes plugin and I would like to reuse some of the test facilities the plugin implements for its own testing.
=> Package kubernetes test jar

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Follow up to #310 
See https://github.com/jenkinsci/kubernetes-plugin/pull/310#issuecomment-396690352 for details.
=> Do not emit empty strings for resource requests/limits

examples/kaniko-declarative.groovy
=> [JENKINS-52576] Add a declarative example for kaniko

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_10/config.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_10/credentials.xml
Addresses upgrade issue for JENKINS-48149
@carlossg ptal
=> [JENKINS-48149] Fix defaults for pod retention on pod templates

src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
=> Add more tests about resources

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
[JENKINS-53370](https://issues.jenkins-ci.org/browse/JENKINS-53370)
=> [JENKINS-53370] Check for nulls in older kubernetes versions

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
Fix findbugs with newer Jenkins versions
=> Check for nulls in agent computer

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Caused by bf7a47847dfb5ef2d1e2a537e2eb9f28063988c6
=> Fix form validation

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Also implement equals/hashcode
=> Add missing field maxRequestsPerHost to copy constructor

README.md
Here is an update to the README to help clarify how to use podTemplates in shared libraries. It took some figuring out to get to the bottom of this as I was seeing the same symptoms as in [JENKINS-49366](https://issues.jenkins-ci.org/browse/JENKINS-49366).
Improving the docs here will hopefully lead to less confusion.
Please let me know if any amendments need to be made.
=> Fix docs for syntax for use of nested podTemplates in shared libraries

CHANGELOG.md
Version referenced in changelog is incorrect, Jenkins dependent version should be 
2.138.4
=> incorrect version inCHANGELOG.md, should read 2.138.4

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Depends on https://github.com/fabric8io/kubernetes-client/pull/1355
On top of #427
=> [JENKINS-50429] Pass the buffer size to kubernetes-client

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
add @DataBoundSetter so values are persisted in config.xml
=> [JENKINS-53532] fix values not persisted

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
=> Prevent a wait forever if websocket is not connected

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
This implement merge of parent yaml fragment with children pod templates.
=> [JENKINS-56082] Merge pod templates definitions from yaml

pom.xml
To fix issue in java 11 javadoc
=> Update parent pom to 3.43

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
[JENKINS-56347](https://issues.jenkins-ci.org/browse/JENKINS-56347)
Debugging multiple pod launches, trying to bisect the change that caused the issue
=> [JENKINS-56347] Wait for agent to connect on provisioning

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
[JENKINS-55123](https://issues.jenkins-ci.org/browse/JENKINS-55123)
=> [JENKINS-55123] Add test for proxy configuration

Jenkinsfile-kubernetes, Jenkinsfile-release
[INFRA-2129](https://issues.jenkins-ci.org/browse/INFRA-2129)
=> [INFRA-2129] Prefer -ntp

Jenkinsfile-kubernetes
=> -ntp cannot be set in MAVEN_OPTS

pom.xml
=> Credentials

pom.xml
=> Update parent POM to 3.44 / Remove surefire override

src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badlabel.groovy
There are reports of test passing when it shouldn't
=> Ensure there are no race conditions running badlabel test

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
Minor code simplification in test.
=> LoggerRule.recordPackage

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
[JENKINS-58374](https://issues.jenkins-ci.org/browse/JENKINS-58374)
=> [JENKINS-58374] Properly merge environment variable lists to avoid duplicates

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-yamlMergeStrategy.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/mergeYaml.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/overrideYaml.groovy
=> [JENKINS-58405] Backward compatibility for yaml field merge

README.md
=> README: Fix the plugin name and add badges

pom.xml, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
Downstream of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/112. Removes a workaround from #552.
=> Demonstrating that an upstream fix avoids the need for a workaround

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-workingDir.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly, src/main/webapp/help/workingDir.html, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/supportComputerEnvVars.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
[JENKINS-58705](https://issues.jenkins-ci.org/browse/JENKINS-58705)
=> [JENKINS-58705] Update default working dir to /home/jenkins/agent

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
See https://github.com/jenkinsci/kubernetes-plugin/pull/562#discussion_r308691551
=> Code review PR 562

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
[JENKINS-58785](https://issues.jenkins-ci.org/browse/JENKINS-58785)
=> [JENKINS-58785] Only define environment variables for agent in jnlp container

pom.xml
Not packaged anymore in this plugin
Amends #591
=> Remove dependency management for jackson-dataformat-yaml

README.md
`POD_LABEL` label wasn't correctly capitalized
=> Fix a typo in the REAME.md

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep/help-shell.html
Includes [JENKINS-57829](https://issues.jenkins-ci.org/browse/JENKINS-57829) as well as some other things. Does _not_ include [JENKINS-57828](https://issues.jenkins-ci.org/browse/JENKINS-57828).
=> /pipeline-syntax/ cleanups

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
As proposed by @Vlatombe [here](https://github.com/jenkinsci/kubernetes-plugin/pull/602#issuecomment-547924630) to solve the issues with jcasc plugin.
=> Switch directConnection default to false

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Amends #649 since it did not work acc. to failures in #654. Resurrecting an earlier attempt.
=> Safepoint flakes, redux

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
[JENKINS-58789](https://issues.jenkins-ci.org/browse/JENKINS-58789)
=> [JENKINS-58789] Properly merge TaskListenerDecorator

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
[JENKINS-60537](https://issues.jenkins-ci.org/browse/JENKINS-60537)
See https://github.com/jenkinsci/kubernetes-plugin/pull/640#commitcomment-36483725
=> [JENKINS-60537] Fix support of pod templates with multiple labels

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
=> Fix some exceptions in reaper when receiving an event while jenkins instance is down

kind.sh
Subsumes #689 and amends #685.
* kubectl 1.17.0
* pick up OS distribution depending on where the script runs
* pull image beforehand then load it in kind
=> Kind improvements

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
See [JENKINS-60733](https://issues.jenkins-ci.org/browse/JENKINS-60733)
Because we have a lot of kubernetes clouds and pods templates, the configuration page of Jenkins is very large and it is difficult to find a specific property. The page is also very long to load.
To solve this, I purpose to add `<advanced>` button to the cloud properties and pod template properties.
=> [JENKINS-60733] Feature/collapse configuration

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
Test output is limited and this prevents seeing the root cause
=> Reduce log verbosity when running tests

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/StandardPlannedNodeBuilder.java
Deprecate PodTemplate#getDisplayName
=> Remove calls to PodTemplate#getDisplayName and use #getName instead.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
=> Remove warning about high number of expired clients

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Had to edit this assertion already in #661 and it is just not worth the maintenance.
=> Do not assert $JNLP_JAVA_HOME

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
Per [feedback](https://github.com/jenkinsci/kubernetes-plugin/pull/600#issuecomment-593317379) from @Vlatombe I have prepared a PR which allows setting of workspaceVolume from a declarative Jenkins pipeline.
I updated the README with a bit of relevant information as well.
=> Allow setting of workspaceVolume in declarative Jenkins pipeline

README.md
Mention list of supported credentials types
=> Improve readme to mention supported credentials types

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html
=> Fix typo, add newline to end of file

pom.xml
Should have been in #760, I just did not get a chance to review that before it was merged.
=> Removing some properties which are unnecessary as of 4.x parent

pom.xml
Testing this before releasing 4.9.1-1
=> Update kubernetes-client-api to 4.9.1-1

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
This INFO logs are spamming log files. Reducing them to FINE seems ok as they are not really giving any specific information (they might be useful for debugging).
=> Too much INFO logging

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Anyway, the agent gets deleted just after.
=> Do not put agent temporarily offline before deleting it

src/main/kubernetes/jenkins.yml
Add selector to yaml file of statefullset
=> Add selector to yaml file of statefullset

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
sometime getting aborted or failed depending on whether there is a
remoting call in flight
=> Relax test check

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/taskListenerAfterRestart.groovy
=> Use a separated test to test taskListener injection after restart

README.md
=> Document required versions of Kubernetes and OpenShift

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
This is causing RestartPipelineTest#taskListenerAfterRestart to fail often (not always, not sure exactly why)
=> Fix cloud resolution for PodTemplateStepExecution#onResume

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapperTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_invalidCredentials.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_missingCredentials.groovy
Regression caused by #682 
Add `kubeconfig` symbol for pipelines. Add some minimal tests
=> [JENKINS-61239] Fix kubectl build wrapper

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
=> When merging containers, only add security context when needed.

pom.xml, src/test/resources/rules.xml
=> Remove explicit versions-maven-plugin

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Makes it easier to get started with development.
=> Add a cloud instance automatically when running in hpi:run mode

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/taskListenerAfterRestart_multipleLabels.groovy
Allows to look up the right pod template for certain on resume.
Replaces #816
=> [JENKINS-63359] Add a unique ID to pod template.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
=> Fix PodTemplate#toString()

pom.xml
No longer needed after #845
Closes #838
=> Remove `workflow-cps` override

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest/emptyKubernetesCloudReadResolve/config.xml
Compatibility fix needed after #828
=> Make sure `containerCap` defaults to Integer.MAX_VALUE when starting from an empty `KubernetesCloud`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/substituteEnv.groovy
=> Test for SECURITY-1646

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
Cherry-pick #880 into `stable-1.27`
=> Backport: Fix template removal

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/263
=> Improve tests logging

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateLabelFilter.java
Improves scalability…up to a point.
=> KubernetesCloud.provision optimizations

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest/readResolveContainerCapZero/config.xml
Amends #866. Serialized 0 means unlimited.
@schottsfired @twasyl @kerogers-cloudbees
=> Handle migration of `containerCap = 0`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
If you have a setup whereby `KUBERNETES_JENKINS_URL` is defined with the in-cluster (e.g., CoreDNS) location of the controller, you have a problem when using external clusters to launch WebSocket agents: there is no way that URL is going to work. You really want the public (ingress) URL. This patch just ignores `KUBERNETES_JENKINS_URL` in that case.
I am limiting the change in behavior to the case that WebSocket is in use, not TCP, and that there are credentials defined in the cloud. Reasoning:
* Use of credentials implies an external cluster. The whole point of `KUBERNETES_JENKINS_URL` is to support agents launched inside the cluster. In this case you are expected to leave credentials blank, so that the controller will use its service account. Keeping credentials to access a cluster in a …
=> getJenkinsUrlOrNull to ignore KUBERNETES_JENKINS_URL when webSocket && credentialsId

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
Remove @Restricted for PodTemplate#getYaml because it may not be necessary
=> Remove @Restricted for PodTemplate#getYaml

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage
=> [JENKINS-63016] feat: new resource - ephemeral storage

examples/kaniko-declarative.groovy, examples/kaniko-gcr.groovy, examples/multi-container.groovy, examples/openshift-home-yaml.groovy, examples/selenium.groovy, src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-args.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-command.html, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy
Changing defaults for command and args in Container Template. Document Windows defaults in the help.
Ticket: [JENKINS-57841](https://issues.jenkins.io/browse/JENKINS-57841)
=> [JENKINS-57841] Change defaults for command and args

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/envVarDollarSignEscaping.groovy
[JENKINS-61950](https://issues.jenkins.io/browse/JENKINS-61950)
=> [JENKINS-61950] [CPLT2-6470] unfixing $$ in env vars for sh step inside a container step

README.md, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
[JENKINS-63627](https://issues.jenkins.io/browse/JENKINS-63627)
I still need to update the README.
=> [JENKINS-63627] container() defines `POD_CONTAINER` in its body with the name of the container

.github/autolabeler.yaml
https://github.com/apps/probot-autolabeler
=> Configure autolabeler

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
kubernetes-client is changing some generics that we were using in tests for no good reason.
=> Prepare update to kubernetes-client by removing imports of class that are going to change

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
https://github.com/jenkinsci/kubernetes-plugin/pull/915#discussion_r575390248
=> [JENKINS-57841] Typo in defaultValue for ttyEnabled

README.md, README_zh.md
=> update jenkins docker image url

Dockerfile, README.md, README_zh.md, src/main/docker/master-executors.groovy, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-image.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-addMasterProxyEnvVars.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-jenkinsUrl.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-podRetention.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-skipTlsVerify.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/config.jelly, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Updating Jenkins master to controller as part of [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398)
=> [JENKINS-65398] terminology update

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Always.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Default.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Never.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/OnFailure.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetention.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java
In some cases, it can cause guice circular dependency issues
=> Avoid depending on Jenkins in `toString()` methods

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
[JENKINS-65453](https://issues.jenkins.io/browse/JENKINS-65453)
When using the container template inheritance feature `livenessProbe` and `shell` attributes were not inherited by the child template.
=> [JENKINS-65453] Inherit LivenessProbe and Shell

README.md
Update documentation link to latest working release 1.20
=> Fix broken link for yaml representation of the Pod

pom.xml
Will be based on kubernetes-client 5.x line (#935)
=> Prepare 1.30.0

README.md
https://github.com/jenkinsci/kubernetes-plugin/pull/993#issuecomment-853363293
=> Clarify docs regarding `command` and `args`

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Downstream of https://github.com/jenkinsci/credentials-binding-plugin/pull/139.
=> Use `SecretPatterns` from `SecretsMasker`

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Backports #935 for Jenkins lines between 2.222.4 (inclusive) and 2.263 (exclusive)
=> [JENKINS-65908] Backport kubernetes-client-api 5.x compatibility for old Jenkins users

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java
```
java.lang.NullPointerException at
org.csanchez.jenkins.plugins.kubernetes.PodUtils.cancelQueueItemFor(PodUtils.java:76) at
org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:152) at
com.cloudbees.jenkins.plugins.kube.ListenableKubernetesLauncher.launch(ListenableKubernetesLauncher.java:30) at
hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294) at
jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) at
jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80) at
java.util.concurrent.FutureTask.run(FutureTask.java:266) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at …
```
=> Guard against potential NPE when a pod couldn't be created

kind.sh, test-in-k8s.sh
=> Update kind to 0.11.1/kubectl 1.21.3

.github/workflows/release-drafter.yml
=> Run release drafter with GH actions

src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodImagePullSecret.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodLabel.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimitsTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateMapTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Fixed some deprecation warnings and minor refactoring:
* replaced comparison to `Objects.equals`
* replaced `Jenkins.getInstance()` with `Jenkins.get()`
* simplified some JUnit asserts
* replaced some for loops with foreach
- [] Link to relevant issues in GitHub or Jira
=> Fixed some deprecation warnings and minor refactoring

src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
At least removing the unhelpful stack trace portion of a repeated error I found in a system log.
```
WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: …, template=PodTemplate{…}], yamls=[apiVersion: v1
kind: Pod
metadata:
annotations:
cluster-autoscaler.kubernetes.io/safe-to-evict: false
spec:
…
, apiVersion: v1
kind: Pod
spec:
…]}
java.lang.IllegalStateException: Pod is no longer available: …/…
at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:124)
at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:153)
at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContai …
```
=> Suppress useless stack trace

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
=> De-flake `KubernetesPipelineTest#terminatedPod`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
=> Remove usage of deprecated class AbstractStepExecutionImpl

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Partial revert of #1073 to restore serial compatibility with 1.30.8 and before.
=> Restore serial compatibility with 1.30.8 and before

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
It could be either terminated, or waiting depending on whether the pod has been deleted already.
=> Just wait for container status to be displayed.

.github/dependabot.yml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
Also update remoting to the current latest, `4.11-1`.
=> Externalize inbound-agent version to a Dockerfile so that it is updated automatically

README.md
=> Add links to the pod model

pom.xml
I'm guessing due to clash betweeen #1098  and #1099
=> Fix requireUpperBoundDeps

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
=> Some `@CheckForNull`s

pom.xml
=> Order requireUpperBoundDeps and document conflicts

README.md
The README file is quite long, so I added a table of content with all "level 1" (one # ) titles.
+ added an entry in the troubleshooting part.
=> README: Adding a troubleshooting entry

README.md
=> Fixing README format, missing quotes.

README.md
Current outlook, https://github.com/jenkinsci/kubernetes-plugin#notedue-to-implementation-constraints-there-can-be-issues-when-executing-commands-in-different-containers-if-they-run-using-different-uidsit-is-recommended-to-use-the-same-uid-across-the-different-containers-part-of-the-same-pod-to-avoid-any-issue
**Note Due to implementation constraints, there can be issues when executing commands in different containers if they run using different uids. It is recommended to use the same uid across the different containers part of the same pod to avoid any issue.**
=> Fix a typo in the format

README.md
This PR updates the Jenkins plugin documentation with the new `dynamicPVC` option that is being added for volumes through [JENKINS-64006](https://issues.jenkins.io/browse/JENKINS-64006).
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> [JENKINS-64006] Documenting dynamicPVC for volumes

README.md
https://github.com/jenkinsci/kubernetes-plugin/pull/336
=> idleMinutes may use in declarative pipelines

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
=> [JENKINS-67100 Init counter if we receive a node deletion earlier

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
=> Ensure yaml > template > cloud for namespace

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
It was unused since https://github.com/jenkinsci/kubernetes-plugin/pull/826
=> Remove dead code

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Follows up #1185 by also improving diagnostics ~if~ now that https://github.com/jenkinsci/jenkins/pull/6585 is merged.
=> Warn when `instance-identity` is missing

pom.xml
Cleanup from #1210 via https://github.com/jenkinsci/bom/pull/1276.
=> Pick up versions from BOM

pom.xml
=> Simplify `dependencyManagement`

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
=> Consistently inject websocket field if computer launcher is a KubernetesLauncher (should always be)

src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy
On top of #1275. https://github.com/jenkinsci/kubernetes-plugin/pull/671#discussion_r765086604
=> Let `runInDynamicallyCreatedContainer` work with cgroups v2

kind.sh, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_invalidCredentials.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_missingCredentials.groovy
This makes sure all images used in various tests are loaded to the kind cluster before actually running the tests.
=> Pre-load test docker images to prevent timeouts during tests

Jenkinsfile, kind.sh, test-in-k8s.sh
Was able to go down to an overall 27m (from initial 44m)
Run CI in parallel to speed up builds.
=> Run CI in parallel

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
=> Slightly relax `runInPodWithMultipleContainers` as it breaks with custom image

Jenkinsfile
https://github.com/jenkinsci/kubernetes-plugin/pull/1292#discussion_r1067193653
Seems to save ~3 minutes (because VM provisioning takes way more time).
=> use a container-based node for the initial split

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineRJRTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineWebsocketRJRTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/basicPipeline.groovy
Re-enable tests depending on RealJenkinsRule.
=> [JENKINS-70392] RealJenkinsRule testing

.github/renovate.json
=> Tweak renovate configuration

.github/renovate.json, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
=> Remove jdk11 suffix from inbound-agent to ease matching

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
[JENKINS-70563](https://issues.jenkins.io/browse/JENKINS-70563) Attempt to fix the problem with wildcards in the Jenkins Proxy not conform to the latest changes in fabric8/k8s-client 6.x. https://github.com/fabric8io/kubernetes-client/issues/4418
Though as mentioned in the method description in this PR, it is not simple to "convert" the Jenkins Proxy configuration - that supports wildcards - to what the k8s client expects. Maybe we could also propose a feature request upstream in k8s-client to support a ProxySelector. in the meantime, this should help.
=> [JENKINS-70563] Adapt proxy configuration to Kubernetes client 6.x

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
In case https://github.com/jenkinsci/kubernetes-plugin/pull/1324 doesn't work and require more investigation time.
=> Ignore `RestartPipelineTest` until I sort out the test issue

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Let's see how to deflake `RestartPipelineTest`
=> Revert "Ignore `RestartPipelineTest` until I sort out the test issue"

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
=> Minor cleanups from SECURITY-3079 fix

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
Fixes an issue introduced by #836 and amends #1320, removing usage of `HttpClientUtils.getProxyUrl` as it got removed in newer version of kubernetes-client.
```[tasklist]
```
=> Map proxy username properly

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Hi kubernetes plugin maintainers!
Please review KubernetesCloudTest fix. In jenkins 2.414 configuration page for kubernetes was moved, so 2 tests start failing. This PR fixes the issue.
```[tasklist]
```
=> fix KubernetesCloudTest as configuration page was moved

pom.xml, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Follow up #1415
Use a more explicit check and add todos to clean up for later.
Verified with
```
mvn test -Dtest=KubernetesCloudTest -Djenkins.version=2.414
```
```[tasklist]
```
=> Follow up #1415

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Review with **Hide Whitespace** enabled
=> Remove unnecessary test branch

pom.xml, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
=> jep-227 downstream usage

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-image.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-name.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-jnlpregistry.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-slaveConnectTimeout.html, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent/help-defaultContainer.html
Replacing _JNLP_ terminology, correcting some outdated information, etc. Supersedes #1455.
=> Refresh of inline docs

pom.xml
Subsumes #1469; supersedes #1345, #1438, & #1468.
=> BOM cleanup

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Split from #1478 
```[tasklist]
```
=> Test robustness fixes

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/LimitRegistrationResults.java
In case the provisioning failed, the corresponding slots accounting for provisioning limits were not freed up.
```[tasklist]
```
=> Properly unregister slots that were reserved during provisioning if the provisioning ended up failing.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java
Some follow-ups on #1513
```[tasklist]
```
=> Follow-up JENKINS-72112; Spotbugs annotations

src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariables.groovy
=> `openjdk` images are deprecated and they have started removing old tags

src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVC.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCVolume.groovy, src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCWorkspaceVolume.groovy
Continues #1549
```[tasklist]
```
=> Label dynamic PVC with same labels as pod; Filter down lists to current test to ease parallel testing.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
=> Fixed a few IDE warnings while poking around this class, and use JDK11 `Set#of`

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/declarative.groovy, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/maven.groovy, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/windows.groovy
Best reviewed ignoring whitespaces.
=> Update code snippets with retry step

src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
https://github.com/jenkinsci/jenkins/pull/9311
=> Remove usages of Commons Compress

src/main/java/org/csanchez/jenkins/plugins/kubernetes/GarbageCollection.java
=> Avoid pod garbage collection thread getting killed because of a common unhandled exception

src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
This allows to wait for some backoff events before considering the backoff is fatal, and avoid transient issues from failing a build.
=> Give more control to cancel build in case of a backoff event.

src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
This makes room for further improvements to the `jenkins-agent` script, for example, setting up a jar cache.
=> Copy the whole `/usr/share/jenkins` path recursively to account for extra files

Jenkinsfile, pom.xml
=> Enable coverage reports

src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/templates.jelly, src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly
=> Migrate from EE 8 to EE 9 in Jelly views

src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java, src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java, src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
This change updates the KubernetesSlave to perform a lookup of the pod when the pod reference is `null`. Usually the Pod reference is assigned at launch. If Jenkins restarts and a Kubernetes agent attempts to reconnect this reference is lost.
A new method `KubernetesCloud#getPodResource` was added to improve testability and encapsulate common lookup operations. Notably not all call sites were checking for the `@Nullable` `namespace` field when calling `.inNamespace()`, which does not accept null values.
=> Fetch Pod reference if unassigned

pom.xml
TEST https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/296
=> Update to Kubernetes client 6.14.0
